In [ ]:
## Python basics for novice data scientists, supported by Wagatsuma Lab@Kyutech 
#
# The MIT License (MIT): Copyright (c) 2020 Hiroaki Wagatsuma and Wagatsuma Lab@Kyutech
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */
#
# # @Time    : 2023-7-1 
# # @Author  : Hiroaki Wagatsuma
# # @Site    : https://github.com/hirowgit/2A_python_basic_course
# # @IDE     : Python 3.10.9 (main, Dec 15 2022, 18:18:30) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
# # @File    : ksp_novice_lec03.py 

In [32]:
import numpy as np
import numpy.matlib
import os
import sys
import codecs
import matplotlib.pyplot as plt
import pandas as pd
from openpyxl import Workbook
import pprint
import datetime

In [33]:
import seaborn as sns 

In [34]:
import plotly.offline
import plotly.express as px
import plotly.graph_objects as go
import plotly.subplots
import squarify

In [ ]:
!pip install sympy
#もし sympyがインストールされてなかったら上述の　コードを実行してください
import sympy as sy

In [7]:
# !pip install sympy
#もし sympyがインストールされてあれば、下記だけで結構です
import sympy as sy

### 簡単な計算

In [35]:
a = 1 
b = a 
a = 2

In [36]:
a,b

(2, 1)

In [37]:
a = [0,0,0] 

a[0]=1
b = a 
a[0] = 2

In [38]:
a[0],b[0]

(2, 2)

In [39]:
a = 1 
b = a 
print(a,b)
a = 2
print(a,b)

1 1
2 1


In [40]:
a = [0] 

a[0]=1
b = a 
print(a[0],b[0])

a[0] = 2
print(a[0],b[0])

1 1
2 2


### 確率の計算 (for 文)

In [42]:
(1 % 2) ==0

False

In [44]:
(2 % 2) ==0

True

In [45]:
(1 % 2) !=0

True

In [28]:
(2 % 2) !=0

False

In [46]:
sy.Rational(1,3)

1/3

In [9]:
sy.Rational(2,4)

1/2

In [47]:
1/3

0.3333333333333333

In [48]:
2/4

0.5

In [49]:
r_2=0
r_even=0
r_odd=0
totalN=0
print(list(range(1,7)))

for i in range(1,7):
    for j in range(1,7):
        totalN=totalN+1
        if ((i+j) %2)==0:
            r_even=r_even+1
        else:
            r_odd=r_odd+1
        if (i+j)==2:
            r_2=r_2+1
        
print(f'合計が偶数である確率は {sy.Rational(r_even,totalN)}')
print(f'合計が奇数である確率は {sy.Rational(r_odd,totalN)}')
print(f'合計が2である確率は      {sy.Rational(r_2,totalN)}')

[1, 2, 3, 4, 5, 6]
合計が偶数である確率は 1/2
合計が奇数である確率は 1/2
合計が2である確率は      1/36


### 確率の計算 (numpy )

In [50]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [51]:
list(range(1,4))

[1, 2, 3]

In [12]:
list(range(1,4))*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [52]:
[[i]*3 for i in range(1,4)]

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [13]:
sum([[i]*3 for i in range(1,4)],[])

[1, 1, 1, 2, 2, 2, 3, 3, 3]

In [14]:
np.stack([[1,1],[2,2]])

array([[1, 1],
       [2, 2]])

In [56]:
print(L3)

[[1 2 3 1 2 3 1 2 3]
 [1 1 1 2 2 2 3 3 3]]


In [53]:
L1=list(range(1,4))*3
L2=sum([[i]*3 for i in range(1,4)],[])
L3=np.stack([L1,L2])
print(L3)

print(f'{np.where(sum(L3)==2)[0]},{np.where((sum(L3) % 2)==0)[0]},{np.where((sum(L3) % 2)!=0)[0]}')

r_2=len(np.where(sum(L3)==2)[0])
r_even=len(np.where((sum(L3) % 2)==0)[0])
r_odd=len(np.where((sum(L3) % 2)!=0)[0])
totalN=len(L1)

print(f'合計が偶数である確率は {sy.Rational(r_even,totalN)}')
print(f'合計が奇数である確率は {sy.Rational(r_odd,totalN)}')
print(f'合計が2である確率は      {sy.Rational(r_2,totalN)}')

[[1 2 3 1 2 3 1 2 3]
 [1 1 1 2 2 2 3 3 3]]
[0],[0 2 4 6 8],[1 3 5 7]
合計が偶数である確率は 5/9
合計が奇数である確率は 4/9
合計が2である確率は      1/9


In [16]:
(np.where((sum(L3) % 2)==0))

(array([0, 2, 4, 6, 8]),)

In [17]:
len(np.where(sum(L3)==2))

1

In [18]:
NofD=4
L1=list(range(1,NofD+1))*NofD
L2=sum([[i]*NofD for i in range(1,NofD+1)],[])
L3=np.stack([L1,L2])
print(L3)

print(f'{np.where(sum(L3)==2)[0]},{np.where((sum(L3) % 2)==0)[0]},{np.where((sum(L3) % 2)!=0)[0]}')

r_2=len(np.where(sum(L3)==2)[0])
r_even=len(np.where((sum(L3) % 2)==0)[0])
r_odd=len(np.where((sum(L3) % 2)!=0)[0])
totalN=len(L1)

print(f'合計が偶数である確率は {sy.Rational(r_even,totalN)}')
print(f'合計が奇数である確率は {sy.Rational(r_odd,totalN)}')
print(f'合計が2である確率は      {sy.Rational(r_2,totalN)}')

[[1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4]
 [1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4]]
[0],[ 0  2  5  7  8 10 13 15],[ 1  3  4  6  9 11 12 14]
合計が偶数である確率は 1/2
合計が奇数である確率は 1/2
合計が2である確率は      1/16


In [19]:
NofD=6
targetN=7
# L1=list(range(1,NofD+1))*NofD
L1=[2,2,2,5,5,5]*NofD

L2=sum([[i]*NofD for i in range(1,NofD+1)],[])
L3=np.stack([L1,L2])
print(L3)

print(f'{np.where(sum(L3)==targetN)[0]},{np.where((sum(L3) % 2)==0)[0]},{np.where((sum(L3) % 2)!=0)[0]}')

r_2=len(np.where(sum(L3)==targetN)[0])
r_even=len(np.where((sum(L3) % 2)==0)[0])
r_odd=len(np.where((sum(L3) % 2)!=0)[0])
totalN=len(L1)

print(f'合計が偶数である確率は {sy.Rational(r_even,totalN)}')
print(f'合計が奇数である確率は {sy.Rational(r_odd,totalN)}')
print(f'合計が2である確率は      {sy.Rational(r_2,totalN)}')

[[2 2 2 5 5 5 2 2 2 5 5 5 2 2 2 5 5 5 2 2 2 5 5 5 2 2 2 5 5 5 2 2 2 5 5 5]
 [1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6 6]]
[ 9 10 11 24 25 26],[ 3  4  5  6  7  8 15 16 17 18 19 20 27 28 29 30 31 32],[ 0  1  2  9 10 11 12 13 14 21 22 23 24 25 26 33 34 35]
合計が偶数である確率は 1/2
合計が奇数である確率は 1/2
合計が2である確率は      1/6


In [20]:
indexD=(np.argwhere(sum(L3)==targetN).T)[0]
print(sum(L3)[indexD])
print(L3[:,indexD])

[7 7 7 7 7 7]
[[5 5 5 2 2 2]
 [2 2 2 5 5 5]]


In [21]:
indexD=np.argwhere(sum(L3)==targetN)
print(sum(L3)[indexD])
print(L3[:,indexD])

[[7]
 [7]
 [7]
 [7]
 [7]
 [7]]
[[[5]
  [5]
  [5]
  [2]
  [2]
  [2]]

 [[2]
  [2]
  [2]
  [5]
  [5]
  [5]]]


In [23]:
NofD1=6
NofD2=2
targetN=7
# L1=list(range(1,NofD+1))*NofD
L1=[2,5]*NofD1

L2=sum([[i]*NofD2 for i in range(1,NofD1+1)],[])
L3=np.stack([L1,L2])
print(L3)

baseP=np.where((L3[0,:]==5)|(L3[1,:]==5))[0]
sumT=np.where(sum(L3[:,baseP])==targetN)[0]


totalN=len(baseP)
sN=len(sumT)
# print(baseP)
print(totalN)

# print(sumT)
print(sN)

pair０=list(zip(L3[0,:],L3[1,:]))
pair1=list(zip(L3[0,baseP],L3[1,baseP]))
pair2=list(zip(L3[0,baseP[sumT]],L3[1,baseP[sumT]]))

print('')
print(f'全パターン {pair0}')
print(f'その数は {len(pair0)}')
print('')
print(f'L1==5 or L2==5: {pair1}')
print(f'その数は {totalN}')
print('')
print(f'L1+L2==7 in the above list: {pair2}')
print(f'その数は {sN}')
print('')
print(f'合計が7である確率は      {sy.Rational(sN,totalN)}')

[[2 5 2 5 2 5 2 5 2 5 2 5]
 [1 1 2 2 3 3 4 4 5 5 6 6]]
7
2

全パターン [(2, 1), (5, 1), (2, 2), (5, 2), (2, 3), (5, 3), (2, 4), (5, 4), (2, 5), (5, 5), (2, 6), (5, 6)]
その数は 12

L1==5 or L2==5: [(5, 1), (5, 2), (5, 3), (5, 4), (2, 5), (5, 5), (5, 6)]
その数は 7

L1+L2==7 in the above list: [(5, 2), (2, 5)]
その数は 2

合計が7である確率は      2/7


In [24]:
L2=sum([[i]*NofD2 for i in range(1,NofD1+1)],[])

L2

[1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6]

### その他

In [38]:
a = 1 
b = a 
print(a,b)
print(str(id(a))+', '+str(id(b)))
a = 2
print(a,b)
print(str(id(a))+', '+str(id(b)))


1 1
4519004464, 4519004464
2 1
4519004496, 4519004464


In [39]:
a = [0,0,0] 

a[0]=1
b = a 
print(a[0],b[0])
print(str(id(a[0]))+', '+str(id(b[0])))

a[0] = 2
print(a[0],b[0])
print(str(id(a[0]))+', '+str(id(b[0])))

1 1
4519004464, 4519004464
2 2
4519004496, 4519004496
