In [ ]:
## Python basics for novice data scientists, supported by Wagatsuma Lab@Kyutech 
#
# The MIT License (MIT): Copyright (c) 2020 Hiroaki Wagatsuma and Wagatsuma Lab@Kyutech
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */
#
# # @Time    : 2023-7-1 
# # @Author  : Hiroaki Wagatsuma
# # @Site    : https://github.com/hirowgit/2A_python_basic_course
# # @IDE     : Python 3.10.9 (main, Dec 15 2022, 18:18:30) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
# # @File    : ksp_novice_lec101.py 

In [1]:
import numpy as np
import numpy.matlib
import os
import sys
import codecs
import matplotlib.pyplot as plt
import pandas as pd
from openpyxl import Workbook
import pprint

## Example 1A

In [815]:
# 例３：インデックスによる集計 
# KIP_bas_lec01_w6 

index=np.random.randint(1, 10, (18,1))
score=np.random.randint(0, 100, (18,1))
B=np.hstack([index,score])
index_sum=np.sum(B[:,0])
score_sum=np.sum(B[:,1])
index1=np.where(index<5)[0]
value_less_than_five=score[index1]
sum_value1=np.sum(value_less_than_five)
index2=np.where(index>=5)[0]
value_five_or_more=score[index2]
sum_value2=np.sum(value_five_or_more)
sum_all=sum_value1+sum_value2
display(score_sum)
display(sum_all)


987

987

In [843]:
# 例３：インデックスによる集計 
# KIP_bas_lec01_w6 
# 単一key

index=np.random.randint(1, 10, (18,1))
score=np.random.randint(0, 100, (18,1))
B=np.hstack([index,score])
index_sum=np.sum(B[:,0])
score_sum=np.sum(B[:,1])

print('index: {0}'.format(index.tolist()))
print('score: {0}'.format(score.tolist()))
print('---')

key=5

index1=np.where(index==key)[0]
value_less_than_five=score[index1]
sum_value1=np.sum(value_less_than_five)
# display(sum_value1)
print('key: {0}, list: {1}, sum: {2}'.format(key, value_less_than_five.tolist(),sum_value1))


index: [[6], [2], [5], [2], [3], [6], [4], [6], [2], [9], [1], [9], [8], [6], [4], [8], [1], [5]]
score: [[79], [32], [23], [36], [19], [18], [49], [58], [97], [75], [30], [51], [0], [31], [21], [64], [97], [10]]
---
key: 5, list: [[23], [10]], sum: 33


In [820]:
sum(index.tolist(),[])

[5, 7, 4, 6, 8, 5, 5, 1, 3, 1, 8, 9, 3, 7, 7, 1, 1, 7]

In [822]:
keyFull=set(index[:,0]) 
keyFull

{1, 3, 4, 5, 6, 7, 8, 9}

In [823]:
keyFull=set(B[:,0])
keyFull

{1, 3, 4, 5, 6, 7, 8, 9}

In [824]:
for key in set(index[:,0]):
    print(key)

1
3
4
5
6
7
8
9


In [842]:
# 例３：インデックスによる集計 
# KIP_bas_lec01_w6 
# 複数key

index=np.random.randint(1, 10, (18,1))
score=np.random.randint(0, 100, (18,1))
B=np.hstack([index,score])
index_sum=np.sum(B[:,0])
score_sum=np.sum(B[:,1])

print('index: {0}'.format(index.tolist()))
print('score: {0}'.format(score.tolist()))
print('---')

for key in set(index[:,0]):#  set(B[:,0]): でも良い
    index1=np.where(index==key)[0]
    value_less_than_five=score[index1]
    sum_value1=np.sum(value_less_than_five)
    print('key: {0}, list: {1}, sum: {2}'.format(key, value_less_than_five.tolist(),sum_value1))


index: [[9], [1], [6], [2], [9], [3], [9], [8], [2], [5], [2], [3], [8], [3], [7], [1], [8], [9]]
score: [[22], [42], [53], [96], [78], [49], [13], [42], [16], [58], [86], [92], [16], [49], [20], [60], [50], [25]]
---
key: 1, list: [[42], [60]], sum: 102
key: 2, list: [[96], [16], [86]], sum: 198
key: 3, list: [[49], [92], [49]], sum: 190
key: 5, list: [[58]], sum: 58
key: 6, list: [[53]], sum: 53
key: 7, list: [[20]], sum: 20
key: 8, list: [[42], [16], [50]], sum: 108
key: 9, list: [[22], [78], [13], [25]], sum: 138


## Example 1B

In [23]:
NofD=10
nPat1D=np.random.randint(1,11,(NofD,1))
nPat2D=np.tile(nPat1D,[1,NofD])
baseN=np.tile(range(1,11),[NofD,1])
key=np.where(nPat2D-baseN==0)

display(nPat1D)
display(nPat2D)
display(baseN)
display(nPat2D-baseN)
display(key)

array([[7],
       [8],
       [8],
       [7],
       [1],
       [5],
       [6],
       [6],
       [5],
       [5]])

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

array([[ 6,  5,  4,  3,  2,  1,  0, -1, -2, -3],
       [ 7,  6,  5,  4,  3,  2,  1,  0, -1, -2],
       [ 7,  6,  5,  4,  3,  2,  1,  0, -1, -2],
       [ 6,  5,  4,  3,  2,  1,  0, -1, -2, -3],
       [ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9],
       [ 4,  3,  2,  1,  0, -1, -2, -3, -4, -5],
       [ 5,  4,  3,  2,  1,  0, -1, -2, -3, -4],
       [ 5,  4,  3,  2,  1,  0, -1, -2, -3, -4],
       [ 4,  3,  2,  1,  0, -1, -2, -3, -4, -5],
       [ 4,  3,  2,  1,  0, -1, -2, -3, -4, -5]])

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([6, 7, 7, 6, 0, 4, 5, 5, 4, 4]))

In [24]:
nPat2D[key]

array([7, 8, 8, 7, 1, 5, 6, 6, 5, 5])

In [25]:
dPat2D=nPat2D*10
dPat2D[key]

array([70, 80, 80, 70, 10, 50, 60, 60, 50, 50])

In [29]:
nPat1D=np.random.randint(1,11,(NofD,1))
nPat2D=np.tile(nPat1D,[1,NofD])
dPat2D=nPat2D*10
display(nPat1D.T)

baseN=np.tile(range(1,11),[NofD,1])
dPat2D[np.where(np.tile(nPat1D,[1,NofD])-np.tile(range(1,11),[NofD,1])==0)]

array([[ 9,  3,  4,  4,  8,  2,  8,  1, 10,  1]])

array([ 90,  30,  40,  40,  80,  20,  80,  10, 100,  10])

In [854]:
index=np.random.randint(1, 10, (18,1))

set(index.T.tolist()[0])

{1, 2, 4, 5, 6, 7, 8, 9}

In [860]:
baseN

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [863]:
uID=set(index.T.tolist()[0])
NofD=len(uID)
uID

{1, 2, 4, 5, 6, 7, 8, 9}

In [869]:
baseN=np.tile(uID,[NofD,1])
baseN

array([[1, 2, 3, 4, 5, 6, 8],
       [1, 2, 3, 4, 5, 6, 8],
       [1, 2, 3, 4, 5, 6, 8],
       [1, 2, 3, 4, 5, 6, 8],
       [1, 2, 3, 4, 5, 6, 8],
       [1, 2, 3, 4, 5, 6, 8],
       [1, 2, 3, 4, 5, 6, 8]])

In [874]:
np.shape(score)

(18, 1)

In [870]:
np.tile(nPat1D,[1,NofD])

array([[ 9,  9,  9,  9,  9,  9,  9],
       [ 3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4],
       [ 4,  4,  4,  4,  4,  4,  4],
       [ 8,  8,  8,  8,  8,  8,  8],
       [ 2,  2,  2,  2,  2,  2,  2],
       [ 8,  8,  8,  8,  8,  8,  8],
       [ 1,  1,  1,  1,  1,  1,  1],
       [10, 10, 10, 10, 10, 10, 10],
       [ 1,  1,  1,  1,  1,  1,  1]])

In [914]:
index

array([[5],
       [7],
       [6],
       [1],
       [9],
       [8],
       [8],
       [7],
       [9],
       [9],
       [9],
       [5],
       [9],
       [7],
       [5],
       [5],
       [6],
       [1]])

In [915]:
score

array([[37],
       [51],
       [66],
       [10],
       [83],
       [81],
       [88],
       [42],
       [ 1],
       [25],
       [19],
       [72],
       [69],
       [43],
       [ 6],
       [62],
       [13],
       [60]])

In [880]:
index=np.random.randint(1, 10, (18,1))
score=np.random.randint(0, 100, (18,1))

In [883]:
B=np.hstack([index,score])
index_sum=np.sum(B[:,0])
score_sum=np.sum(B[:,1])

print('index: {0}'.format(index.tolist()))
print('score: {0}'.format(score.tolist()))
print('---')

for key in set(index[:,0]):#  set(B[:,0]): でも良い
    index1=np.where(index==key)[0]
    value_less_than_five=score[index1]
    sum_value1=np.sum(value_less_than_five)
    print('key: {0}, list: {1}, sum: {2}'.format(key, value_less_than_five.tolist(),sum_value1))


index: [[5], [7], [6], [1], [9], [8], [8], [7], [9], [9], [9], [5], [9], [7], [5], [5], [6], [1]]
score: [[37], [51], [66], [10], [83], [81], [88], [42], [1], [25], [19], [72], [69], [43], [6], [62], [13], [60]]
---
key: 1, list: [[10], [60]], sum: 70
key: 5, list: [[37], [72], [6], [62]], sum: 177
key: 6, list: [[66], [13]], sum: 79
key: 7, list: [[51], [42], [43]], sum: 136
key: 8, list: [[81], [88]], sum: 169
key: 9, list: [[83], [1], [25], [19], [69]], sum: 197


In [910]:
# index=np.random.randint(1, 10, (18,1))
# score=np.random.randint(0, 100, (18,1))

uID=list(set(index.T.tolist()[0]))
NofD=len(uID)
NofD2=len(index)
dPat2D=np.tile(score,[1,NofD])

ext2D=np.full(np.shape(dPat2D),0,dtype=int)
ext2D[np.tile(index,[1,NofD])-np.tile(uID,[NofD2,1])==0]=dPat2D[np.tile(index,[1,NofD])-np.tile(uID,[NofD2,1])==0]
display(np.vstack([np.array(uID),np.sum(ext2D,axis=0)]))

array([[  1,   5,   6,   7,   8,   9],
       [ 70, 177,  79, 136, 169, 197]])

In [911]:
# index=np.random.randint(1, 10, (18,1))
# score=np.random.randint(0, 100, (18,1))

uID=list(set(index.T.tolist()[0]))
NofD=len(uID)
NofD2=len(index)
nPat2D=np.tile(index,[1,NofD])
dPat2D=np.tile(score,[1,NofD])

ext2D=np.full(np.shape(dPat2D),0,dtype=int)
ext2D[nPat2D-np.tile(uID,[NofD2,1])==0]=dPat2D[nPat2D-np.tile(uID,[NofD2,1])==0]
display(np.vstack([np.array(uID),np.sum(ext2D,axis=0)]))

array([[  1,   5,   6,   7,   8,   9],
       [ 70, 177,  79, 136, 169, 197]])

In [889]:
uID

[1, 5, 6, 7, 8, 9]

In [909]:
nPat2D

array([[5, 5, 5, 5, 5, 5],
       [7, 7, 7, 7, 7, 7],
       [6, 6, 6, 6, 6, 6],
       [1, 1, 1, 1, 1, 1],
       [9, 9, 9, 9, 9, 9],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [7, 7, 7, 7, 7, 7],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [5, 5, 5, 5, 5, 5],
       [9, 9, 9, 9, 9, 9],
       [7, 7, 7, 7, 7, 7],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6],
       [1, 1, 1, 1, 1, 1]])

In [916]:
dPat2D

array([[37, 37, 37, 37, 37, 37],
       [51, 51, 51, 51, 51, 51],
       [66, 66, 66, 66, 66, 66],
       [10, 10, 10, 10, 10, 10],
       [83, 83, 83, 83, 83, 83],
       [81, 81, 81, 81, 81, 81],
       [88, 88, 88, 88, 88, 88],
       [42, 42, 42, 42, 42, 42],
       [ 1,  1,  1,  1,  1,  1],
       [25, 25, 25, 25, 25, 25],
       [19, 19, 19, 19, 19, 19],
       [72, 72, 72, 72, 72, 72],
       [69, 69, 69, 69, 69, 69],
       [43, 43, 43, 43, 43, 43],
       [ 6,  6,  6,  6,  6,  6],
       [62, 62, 62, 62, 62, 62],
       [13, 13, 13, 13, 13, 13],
       [60, 60, 60, 60, 60, 60]])

In [917]:
ext2D=np.full(np.shape(dPat2D),0,dtype=int)
ext2D

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [921]:
np.tile(uID,[NofD2,1])

array([[1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9],
       [1, 5, 6, 7, 8, 9]])

In [908]:
# index=np.random.randint(1, 10, (18,1))
# score=np.random.randint(0, 100, (18,1))

uID=list(set(index.T.tolist()[0]))
NofD=len(uID)
NofD2=len(index)
nPat2D=np.tile(index,[1,NofD])
dPat2D=np.tile(score,[1,NofD])

ext2D=np.full(np.shape(dPat2D),0,dtype=int)
ext2D[np.tile(index,[1,NofD])-np.tile(uID,[NofD2,1])==0]=dPat2D[np.tile(index,[1,NofD])-np.tile(uID,[NofD2,1])==0]
display(np.vstack([np.array(uID),np.sum(ext2D,axis=0)]))

array([[  1,   5,   6,   7,   8,   9],
       [ 70, 177,  79, 136, 169, 197]])

In [907]:
display(np.vstack([np.array(uID),np.sum(ext2D,axis=0)]))

array([[  1,   5,   6,   7,   8,   9],
       [ 70, 177,  79, 136, 169, 197]])

In [923]:
ext2D=np.full(np.shape(dPat2D),0,dtype=int)
ext2D
ext2D[np.tile(index,[1,NofD])-np.tile(uID,[NofD2,1])==0]=nPat2D[np.tile(index,[1,NofD])-np.tile(uID,[NofD2,1])==0]
display(ext2D)

ext2D=np.full(np.shape(dPat2D),0,dtype=int)
ext2D
ext2D[np.tile(index,[1,NofD])-np.tile(uID,[NofD2,1])==0]=dPat2D[np.tile(index,[1,NofD])-np.tile(uID,[NofD2,1])==0]
display(ext2D)
np.sum(ext2D,axis=0)

array([[0, 5, 0, 0, 0, 0],
       [0, 0, 0, 7, 0, 0],
       [0, 0, 6, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 8, 0],
       [0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 9],
       [0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 9],
       [0, 0, 0, 7, 0, 0],
       [0, 5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0],
       [0, 0, 6, 0, 0, 0],
       [1, 0, 0, 0, 0, 0]])

array([[ 0, 37,  0,  0,  0,  0],
       [ 0,  0,  0, 51,  0,  0],
       [ 0,  0, 66,  0,  0,  0],
       [10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 83],
       [ 0,  0,  0,  0, 81,  0],
       [ 0,  0,  0,  0, 88,  0],
       [ 0,  0,  0, 42,  0,  0],
       [ 0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0, 25],
       [ 0,  0,  0,  0,  0, 19],
       [ 0, 72,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 69],
       [ 0,  0,  0, 43,  0,  0],
       [ 0,  6,  0,  0,  0,  0],
       [ 0, 62,  0,  0,  0,  0],
       [ 0,  0, 13,  0,  0,  0],
       [60,  0,  0,  0,  0,  0]])

array([ 70, 177,  79, 136, 169, 197])

In [913]:
print(ext2D)

[[ 0 37  0  0  0  0]
 [ 0  0  0 51  0  0]
 [ 0  0 66  0  0  0]
 [10  0  0  0  0  0]
 [ 0  0  0  0  0 83]
 [ 0  0  0  0 81  0]
 [ 0  0  0  0 88  0]
 [ 0  0  0 42  0  0]
 [ 0  0  0  0  0  1]
 [ 0  0  0  0  0 25]
 [ 0  0  0  0  0 19]
 [ 0 72  0  0  0  0]
 [ 0  0  0  0  0 69]
 [ 0  0  0 43  0  0]
 [ 0  6  0  0  0  0]
 [ 0 62  0  0  0  0]
 [ 0  0 13  0  0  0]
 [60  0  0  0  0  0]]


In [922]:
np.where(np.tile(index,[1,NofD])-np.tile(uID,[NofD2,1])==0)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17]),
 array([1, 3, 2, 0, 5, 4, 4, 3, 5, 5, 5, 1, 5, 3, 1, 1, 2, 0]))

In [919]:
np.tile(index,[1,NofD]),dPat2D

(array([[5, 5, 5, 5, 5, 5],
        [7, 7, 7, 7, 7, 7],
        [6, 6, 6, 6, 6, 6],
        [1, 1, 1, 1, 1, 1],
        [9, 9, 9, 9, 9, 9],
        [8, 8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8, 8],
        [7, 7, 7, 7, 7, 7],
        [9, 9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9, 9],
        [5, 5, 5, 5, 5, 5],
        [9, 9, 9, 9, 9, 9],
        [7, 7, 7, 7, 7, 7],
        [5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6],
        [1, 1, 1, 1, 1, 1]]),
 array([[37, 37, 37, 37, 37, 37],
        [51, 51, 51, 51, 51, 51],
        [66, 66, 66, 66, 66, 66],
        [10, 10, 10, 10, 10, 10],
        [83, 83, 83, 83, 83, 83],
        [81, 81, 81, 81, 81, 81],
        [88, 88, 88, 88, 88, 88],
        [42, 42, 42, 42, 42, 42],
        [ 1,  1,  1,  1,  1,  1],
        [25, 25, 25, 25, 25, 25],
        [19, 19, 19, 19, 19, 19],
        [72, 72, 72, 72, 72, 72],
        [69, 69, 69, 69, 69, 69],
        [43, 43, 43, 43, 43, 43],
        [ 6,  6,  

In [901]:
# index=np.random.randint(1, 10, (18,1))
# score=np.random.randint(0, 100, (18,1))

uID=list(set(index.T.tolist()[0]))
NofD=len(uID)
NofD2=len(index)
nPat2D=np.tile(index,[1,NofD])
print('index:')
display(index)
print('index(unique):')
display(uID)
print('extended to 2D:')
display(nPat2D)

dPat2D=np.tile(score,[1,NofD])
display(dPat2D)

baseN=np.tile(uID,[NofD,1])

# np.where(np.tile(index,[1,NofD])-np.tile(uID,[NofD2,1])==0)]
dPat2D[np.tile(index,[1,NofD])-np.tile(uID,[NofD2,1])==0]

# dPat2D[np.where(np.tile(nPat1D,[1,NofD])-np.tile(uID,[NofD,1])==0)]

index:


array([[5],
       [7],
       [6],
       [1],
       [9],
       [8],
       [8],
       [7],
       [9],
       [9],
       [9],
       [5],
       [9],
       [7],
       [5],
       [5],
       [6],
       [1]])

index(unique):


[1, 5, 6, 7, 8, 9]

extended to 2D:


array([[5, 5, 5, 5, 5, 5],
       [7, 7, 7, 7, 7, 7],
       [6, 6, 6, 6, 6, 6],
       [1, 1, 1, 1, 1, 1],
       [9, 9, 9, 9, 9, 9],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [7, 7, 7, 7, 7, 7],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [5, 5, 5, 5, 5, 5],
       [9, 9, 9, 9, 9, 9],
       [7, 7, 7, 7, 7, 7],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6],
       [1, 1, 1, 1, 1, 1]])

array([[37, 37, 37, 37, 37, 37],
       [51, 51, 51, 51, 51, 51],
       [66, 66, 66, 66, 66, 66],
       [10, 10, 10, 10, 10, 10],
       [83, 83, 83, 83, 83, 83],
       [81, 81, 81, 81, 81, 81],
       [88, 88, 88, 88, 88, 88],
       [42, 42, 42, 42, 42, 42],
       [ 1,  1,  1,  1,  1,  1],
       [25, 25, 25, 25, 25, 25],
       [19, 19, 19, 19, 19, 19],
       [72, 72, 72, 72, 72, 72],
       [69, 69, 69, 69, 69, 69],
       [43, 43, 43, 43, 43, 43],
       [ 6,  6,  6,  6,  6,  6],
       [62, 62, 62, 62, 62, 62],
       [13, 13, 13, 13, 13, 13],
       [60, 60, 60, 60, 60, 60]])

array([37, 51, 66, 10, 83, 81, 88, 42,  1, 25, 19, 72, 69, 43,  6, 62, 13,
       60])

In [845]:
nPat1D

array([[ 9],
       [ 3],
       [ 4],
       [ 4],
       [ 8],
       [ 2],
       [ 8],
       [ 1],
       [10],
       [ 1]])

## Example 2

In [33]:
for i in range(9,6,-1):
    print(i)

9
8
7


In [36]:
list(range(9,0,-1))

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [41]:
rd = list(range(9,0,-1))
rn = []
while len(rn) < 2:
    key = np.random.randint(0,len(rd))
    n=rd.pop(key)
    rn.extend([n])
rn

[2, 5]

In [49]:
rn=list(range(1,10))
rn

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [52]:
display(rn)
k=4
rn.pop(k-1)
display(rn)

[1, 2, 3, 6, 7, 8, 9]

[1, 2, 3, 7, 8, 9]

In [69]:
ns=set(range(0,9))
ns

{0, 1, 2, 3, 4, 5, 6, 7, 8}

In [61]:
ns=ns-{1}
ns

set()

In [74]:
reversed(sorted(list(ns)))

In [71]:
a=list(ns).sort(reverse=True)
print(a)

None


In [76]:
ns=set(range(0,9))
for i in reversed(sorted(list(ns))):
    ns=ns-{i}
    ns
    print(ns)
    print(i)

{0, 1, 2, 3, 4, 5, 6, 7}
8
{0, 1, 2, 3, 4, 5, 6}
7
{0, 1, 2, 3, 4, 5}
6
{0, 1, 2, 3, 4}
5
{0, 1, 2, 3}
4
{0, 1, 2}
3
{0, 1}
2
{0}
1
set()
0


In [81]:
ns=set(range(0,9))
for i in reversed(sorted(list(ns))):
    ns=ns-{i}
    for j in reversed(sorted(list(ns))):
        a=map(lambda x: i+j+x, list(ns-{j}))
        print(list(a))
    print(ns)
    print(i)

[15, 16, 17, 18, 19, 20, 21]
[14, 15, 16, 17, 18, 19, 21]
[13, 14, 15, 16, 17, 19, 20]
[12, 13, 14, 15, 17, 18, 19]
[11, 12, 13, 15, 16, 17, 18]
[10, 11, 13, 14, 15, 16, 17]
[9, 11, 12, 13, 14, 15, 16]
[9, 10, 11, 12, 13, 14, 15]
{0, 1, 2, 3, 4, 5, 6, 7}
8
[13, 14, 15, 16, 17, 18]
[12, 13, 14, 15, 16, 18]
[11, 12, 13, 14, 16, 17]
[10, 11, 12, 14, 15, 16]
[9, 10, 12, 13, 14, 15]
[8, 10, 11, 12, 13, 14]
[8, 9, 10, 11, 12, 13]
{0, 1, 2, 3, 4, 5, 6}
7
[11, 12, 13, 14, 15]
[10, 11, 12, 13, 15]
[9, 10, 11, 13, 14]
[8, 9, 11, 12, 13]
[7, 9, 10, 11, 12]
[7, 8, 9, 10, 11]
{0, 1, 2, 3, 4, 5}
6
[9, 10, 11, 12]
[8, 9, 10, 12]
[7, 8, 10, 11]
[6, 8, 9, 10]
[6, 7, 8, 9]
{0, 1, 2, 3, 4}
5
[7, 8, 9]
[6, 7, 9]
[5, 7, 8]
[5, 6, 7]
{0, 1, 2, 3}
4
[5, 6]
[4, 6]
[4, 5]
{0, 1, 2}
3
[3]
[3]
{0, 1}
2
[]
{0}
1
set()
0


In [104]:
ns=set(range(1,10))
ns

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [106]:
len(rItem)

0

In [115]:
# sItem=[]
sItem.append([1,1,1])
sItem

[1, 1, 1, 1, 1, 1, 1, 1, 1, [1, 1, 1]]

In [131]:
sItem=[]
ns=set(range(1,10))
for i in reversed(sorted(list(ns))):
    ns=ns-{i}
    ns2=ns.copy()
    for j in reversed(sorted(list(ns2))):
        tmpL=np.array(list(ns2-{j}))
#         print(tmpL)
        rItem=tmpL[np.where(tmpL+i+j==15)]
        if len(rItem)>0:
            [sItem.append(sorted([i,j,k])) for k in list(rItem)]
#             ns=ns-{j}
#             ns=ns-set(rItem)
            ns2=ns2-set(rItem)
            
#         a=np.where(np.array(list(ns-{j}))+i+j==15)[0]
#         a=map(lambda x: i+j+x, list(ns-{j}))
#         print(a)
#     print(ns)
#     print(i)
print(sItem)

sItem.sort()

for kk in sItem:
    print(sum(kk))

[[1, 5, 9], [2, 4, 9], [2, 4, 9], [1, 5, 9], [1, 6, 8], [2, 5, 8], [3, 4, 8], [3, 4, 8], [2, 5, 8], [1, 6, 8], [2, 6, 7], [3, 5, 7], [3, 5, 7], [2, 6, 7], [4, 5, 6], [4, 5, 6]]
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15
15


In [679]:
# 足したら15になる３つの数字の組み合わせ（数列）の全探索

sItem=[]
for i in range(9,2,-1):
    for j in range(i-1,1,-1):
        for k in range(j-1,0,-1):
            if (i+j+k)==15:
                print(i,j,k)
                sItem.append([i,j,k])
display(sItem) 


9 5 1
9 4 2
8 6 1
8 5 2
8 4 3
7 6 2
7 5 3
6 5 4


[[9, 5, 1],
 [9, 4, 2],
 [8, 6, 1],
 [8, 5, 2],
 [8, 4, 3],
 [7, 6, 2],
 [7, 5, 3],
 [6, 5, 4]]

[1, 1, 2, 2, 2, 3, 3, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7, 8, 8, 8, 9, 9]

In [677]:
# 同じ数が何個使われているか数える（ランキング）

import collections

sItem_flat=sorted(sum(sItem,[]))
display(sItem_flat)

countL = collections.Counter(sItem_flat)
display(countL)
rankList=countL.most_common()
print(rankList)

Counter({1: 2, 2: 3, 3: 2, 4: 3, 5: 4, 6: 3, 7: 2, 8: 3, 9: 2})

[(5, 4), (2, 3), (4, 3), (6, 3), (8, 3), (1, 2), (3, 2), (7, 2), (9, 2)]


In [678]:
np.where(np.array(rankList)[:,1]>=4)

(array([0]),)

In [682]:
targetID=np.array([5,1])
targetID

array([5, 1])

In [688]:
# 足して15になる数列に４回以上使われている数字を探す

rankList_NP=np.array(rankList)
targetID=rankList_NP[rankList_NP[:,1]>=4][:,0]
display(targetID)

# targetID=np.array([5,1])

sVec=[]
for v1 in targetID:
    sVec=sVec+[v for v in sItem if v1 in v]
    
display(sVec)

array([5])

[[9, 5, 1], [8, 5, 2], [7, 5, 3], [6, 5, 4]]

In [684]:
targetID

array([5, 1])

In [662]:
rankList_NP=np.array(rankList)
rankList_NP=np.vstack([rankList_NP[0],rankList_NP])
display(rankList_NP)
rankList_NP[rankList_NP[:,1]>=4][:,0]

array([[5, 4],
       [5, 4],
       [2, 3],
       [4, 3],
       [6, 3],
       [8, 3],
       [1, 2],
       [3, 2],
       [7, 2],
       [9, 2]])

array([5, 5])

In [640]:
sampleD=np.array([9, 5, 1])
display(sampleD)
baseM=np.full((3,3),0)
# b([0,1,2],[0,1,2])
np.where(b==0)
# b[[0,1,2],[0,1,2]]=a
display(baseM)
# g=np.array([[0,1,2],[0,1,2]])
# b[g]=a
# b
row=[[0,1,2],[0,1,2],[0,1,2],[1,1,1]]
col=[[0,1,2],[2,1,0],[1,1,1],[0,1,2]]
k=2
baseM[row[k],col[k]]=a
display(baseM)

display(np.sum(b,axis=0)[[0,2]])
display(np.sum(b,axis=1)[[0,2]])

array([9, 5, 1])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

array([[0, 9, 0],
       [0, 5, 0],
       [0, 1, 0]])

array([0, 0])

array([9, 1])

In [543]:
np.hstack([np.sum(baseM,axis=0)[[0,2]],np.sum(baseM,axis=1)[[0,2]]])==np.tile(15,4)

array([False, False, False, False])

In [544]:
all(np.hstack([np.sum(baseM,axis=0)[[0,2]],np.sum(baseM,axis=1)[[0,2]]])==np.tile(15,4))

False

In [203]:
all([True,True,True,True])

True

In [204]:
all([True,True,True,False])

False

In [547]:
sVec=[[9, 5, 1],
 [8, 5, 2],
 [7, 5, 3],
 [6, 5, 4]]

In [545]:
list(map(lambda x: sorted(x),baseM))

[[0, 0, 9], [0, 0, 5], [0, 0, 1]]

In [689]:
sVecFull=sVec+list(map(lambda x: sorted(x),sVec))
sVecFull

[[9, 5, 1],
 [8, 5, 2],
 [7, 5, 3],
 [6, 5, 4],
 [1, 5, 9],
 [2, 5, 8],
 [3, 5, 7],
 [4, 5, 6]]

In [549]:
baseM=np.full((3,3),0)
row=[[0,1,2],[0,1,2],[0,1,2],[1,1,1]]
col=[[0,1,2],[2,1,0],[1,1,1],[0,1,2]]

rn=[3, 1, 4, 2]
for k in range(4):
    baseM[row[k],col[k]]=sVecFull[rn[k]]
# baseM       
all(np.hstack([np.sum(baseM,axis=0)[[0,2]],np.sum(baseM,axis=1)[[0,2]]])==np.tile(15,4))
display(baseM)

array([[6, 1, 8],
       [7, 5, 3],
       [2, 9, 4]])

In [690]:
baseM=np.full((3,3),0)
row=[[0,1,2],[0,1,2],[0,1,2],[1,1,1]]
col=[[0,1,2],[2,1,0],[1,1,1],[0,1,2]]

# 受講生のアイディアをお借りしました ~~~
LofD=8
TofD=4
rd =list(range(1,LofD))
rn = []
while len(rn) < TofD:
    key = np.random.randint(0,len(rd))
    n=rd.pop(key)
    rn.extend([n])
# ~~~ここまで~~~

# rn=[3, 1, 4, 2]
rn=[2, 3, 5, 7]
rn=[6, 7, 1, 3]
rn=[3, 5, 2, 4]
for k in range(4):
    baseM[row[k],col[k]]=sVecFull[rn[k]]
baseM       
if all(np.hstack([np.sum(baseM,axis=0)[[0,2]],np.sum(baseM,axis=1)[[0,2]]])==np.tile(15,4)):
    display(baseM)
    display(rn)

array([[6, 7, 2],
       [1, 5, 9],
       [8, 3, 4]])

[3, 5, 2, 4]

In [696]:
baseM=np.full((3,3),0)
row=[[0,1,2],[0,1,2],[0,1,2],[1,1,1]]
col=[[0,1,2],[2,1,0],[1,1,1],[0,1,2]]

LofD=7
TofD=4
    
loopN=0

while not all(np.hstack([np.sum(baseM,axis=0)[[0,2]],np.sum(baseM,axis=1)[[0,2]]])==np.tile(15,4)):
    # ~~~受講生のアイディアをお借りしました ~~~
    rd =list(range(LofD))
    rn = []
    while len(rn) < TofD:
        key = np.random.randint(0,len(rd))
        n=rd.pop(key)
        rn.extend([n])
    # ~~~ここまで~~~
    
    for k in range(4):
        baseM[row[k],col[k]]=sVecFull[rn[k]]
    loopN=loopN+1

# baseM       
# if all(np.hstack([np.sum(baseM,axis=0)[[0,2]],np.sum(baseM,axis=1)[[0,2]]])==np.tile(15,4)):
display(baseM)
display(rn)
display(loopN)

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

[1, 3, 4, 6]

56

In [697]:
baseM=np.full((3,3),0)
row=[[0,1,2],[0,1,2],[0,1,2],[1,1,1]]
col=[[0,1,2],[2,1,0],[1,1,1],[0,1,2]]

LofD=4
TofD=4
    
loopN=0

while not all(np.hstack([np.sum(baseM,axis=0)[[0,2]],np.sum(baseM,axis=1)[[0,2]]])==np.tile(15,4)):
    # ~~~受講生のアイディアをお借りしました ~~~
    rd =list(range(LofD))
    rn = []
    while len(rn) < TofD:
        key = np.random.randint(0,len(rd))
        n=rd.pop(key)
        rn.extend([n])
    # ~~~ここまで~~~
    
    for k in range(4):
        if bool(np.random.randint(2)):
            baseM[row[k],col[k]]=sVec[rn[k]]
        else:
            baseM[row[k],col[k]]=sVec[rn[k]][::-1]    
    loopN=loopN+1

# baseM       
# if all(np.hstack([np.sum(baseM,axis=0)[[0,2]],np.sum(baseM,axis=1)[[0,2]]])==np.tile(15,4)):
display(baseM)
display(rn)
display(loopN)

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

[1, 3, 0, 2]

21

In [694]:
rn[k]

4

In [1179]:
# statistical analysis 1: 8*7*6*5 = 1680

from pytictoc import TicToc
t = TicToc() #create instance of class
t.tic() #Start timer

# baseM=np.full((3,3),0)
row=[[0,1,2],[0,1,2],[0,1,2],[1,1,1]]
col=[[0,1,2],[2,1,0],[1,1,1],[0,1,2]]

LofD=7
TofD=4
    
verifyD=[]    
for verifyL in range(1000):
    loopN=0
    baseM=np.full((3,3),0)
    while not all(np.hstack([np.sum(baseM,axis=0)[[0,2]],np.sum(baseM,axis=1)[[0,2]]])==np.tile(15,4)):
        # ~~~受講生のアイディアをお借りしました ~~~
        rd =list(range(LofD))
        rn = []
        while len(rn) < TofD:
            key = np.random.randint(0,len(rd))
            n=rd.pop(key)
            rn.extend([n])
        # ~~~ここまで~~~

        for k in range(4):
            baseM[row[k],col[k]]=sVecFull[rn[k]]
        loopN=loopN+1
    verifyD.extend([loopN])
#     display(loopN)

# display(baseM)
# display(rn)
# display(loopN)

# np.mean(verifyD)
# display(verifyD)

print(np.mean(verifyD))
t.toc() #Time elapsed since t.tic()
etime=t.tocvalue()
display(etime/3600)
display(baseM)

199.507
Elapsed time is 7.667171 seconds.


0.002129784154999975

array([[2, 7, 6],
       [9, 5, 1],
       [4, 3, 8]])

In [636]:
display(8*7*6*5)
display(8*7*6*5/2)

1680

840.0

In [1182]:
# statistical analysis 2: 4*3*2*1*2*2*2*2 = 384

from pytictoc import TicToc
t = TicToc() #create instance of class
t.tic() #Start timer

# baseM=np.full((3,3),0)
row=[[0,1,2],[0,1,2],[0,1,2],[1,1,1]]
col=[[0,1,2],[2,1,0],[1,1,1],[0,1,2]]


LofD=4
TofD=4
    
verifyD=[]    
for verifyL in range(1000):
    loopN=0
    baseM=np.full((3,3),0)
    while not all(np.hstack([np.sum(baseM,axis=0)[[0,2]],np.sum(baseM,axis=1)[[0,2]]])==np.tile(15,4)):
        # ~~~受講生のアイディアをお借りしました ~~~
        rd =list(range(LofD))
        rn = []
        while len(rn) < TofD:
            key = np.random.randint(0,len(rd))
            n=rd.pop(key)
            rn.extend([n])
        # ~~~ここまで~~~

        for k in range(4):
            if bool(np.random.randint(2)):
                baseM[row[k],col[k]]=sVec[rn[k]]
            else:
                baseM[row[k],col[k]]=sVec[rn[k]][::-1]    
        loopN=loopN+1
        verifyD.extend([loopN])

# display(baseM)
# display(rn)
# display(loopN)

# np.mean(verifyD)

print(np.mean(verifyD))
t.toc() #Time elapsed since t.tic()
etime=t.tocvalue()
display(etime/3600)
display(baseM)

46.10137685510852
Elapsed time is 2.258529 seconds.


0.0006273806711154369

array([[8, 3, 4],
       [1, 5, 9],
       [6, 7, 2]])

In [927]:
9*8*7*6*5*4*3*2*1

362880

In [1258]:
4*3*2*1*2*2*2*2

384

In [953]:
from pytictoc import TicToc
t = TicToc() #create instance of class
t.tic() #Start timer

LofD=9
TofD=9
rd =list(range(1,LofD+1))
rn = []
while len(rn) < TofD:
    key = np.random.randint(0,len(rd))
    n=rd.pop(key)
    rn.extend([n])

baseM=np.reshape(rn, (3, 3))
display(baseM)
np.sum(baseM,axis=0)
display(np.diag(baseM))
display(np.diag(np.fliplr(baseM)))
display(np.hstack([np.sum(baseM,axis=0),np.sum(baseM,axis=1),np.sum(np.diag(baseM)),np.sum(np.diag(np.fliplr(baseM)))]))
all(np.hstack([np.sum(baseM,axis=0),np.sum(baseM,axis=1),np.sum(np.diag(baseM)),np.sum(np.diag(np.fliplr(baseM)))])==np.tile(15,8))

# all(np.hstack([np.sum(baseM,axis=0)[[0,2]],np.sum(baseM,axis=1)[[0,2]]])==np.tile(15,4))

t.toc() #Time elapsed since t.tic()

array([[2, 7, 9],
       [8, 6, 3],
       [4, 1, 5]])

array([2, 6, 5])

array([9, 6, 4])

array([14, 14, 17, 18, 17, 10, 13, 19])

Elapsed time is 0.004395 seconds.


In [945]:
np.hstack([np.sum(baseM,axis=0),np.sum(baseM,axis=1),np.diag(baseM),np.diag(np.fliplr(baseM))])

array([14, 20, 11,  9, 15, 21,  3,  9,  8,  1,  9,  7])

In [1001]:
from pytictoc import TicToc
t = TicToc() #create instance of class
t.tic() #Start timer

rn=np.random.choice(range(1, 10), size=9, replace=False)

t.toc() #Time elapsed since t.tic()


Elapsed time is 0.000753 seconds.


In [999]:
from pytictoc import TicToc
t = TicToc() #create instance of class
t.tic() #Start timer

 # ~~~受講生のアイディアをお借りしました ~~~
rd =list(range(LofD))
rn = []
while len(rn) < TofD:
    key = np.random.randint(0,len(rd))
    n=rd.pop(key)
    rn.extend([n])
# ~~~ここまで~~~
rn

t.toc() #Time elapsed since t.tic()


Elapsed time is 0.000409 seconds.


In [1000]:
0.000400/0.000409

0.9779951100244498

In [1142]:
from pytictoc import TicToc
t = TicToc() #create instance of class
# t.tic() #Start timer

verifyT=[] 
verifyD=[]    
for i in range(1000):
    t.tic()
     # ~~~受講生のアイディアをお借りしました ~~~
    rn=np.random.choice(range(1, 10), size=9, replace=False)
    # ~~~ここまで~~~
    etime=t.tocvalue()
    verifyT.extend([etime])
    verifyD.extend([rn])
    
# t.toc() #Time elapsed since t.tic()
print('{:.5f}[ms]'.format(np.mean(verifyT)*1000))

0.02225[ms]


In [1143]:
# vector based cosine_similarity function

cosine_similarity=lambda M1,M2:  np.dot(M1,M2.T)/(np.tile(np.array([np.linalg.norm(M1,axis=1)]).T,[1,len(M2)])*np.tile(np.linalg.norm(M2,axis=1),[len(M1),1]))

In [1144]:
verifyD_NP=np.array(verifyD)
csVec=cosine_similarity(verifyD_NP,verifyD_NP)
csVec2=csVec-np.eye(len(csVec))
list(csVec2.flat)

csVec2int=np.round(np.array(csVec.flat)*10)
countL = collections.Counter(csVec2int)
display(countL)
rankList=countL.most_common()
print(rankList)

Counter({10.0: 11902, 7.0: 275704, 8.0: 474610, 9.0: 208648, 6.0: 29136})

[(8.0, 474610), (7.0, 275704), (9.0, 208648), (6.0, 29136), (10.0, 11902)]


In [1145]:
from pytictoc import TicToc
t = TicToc() #create instance of class
# t.tic() #Start timer

verifyT=[] 
verifyD=[]    
for i in range(1000):
    t.tic()
    # ~~~受講生のアイディアをお借りしました ~~~
    rd =list(range(LofD))
    rn = []
    while len(rn) < TofD:
        key = np.random.randint(0,len(rd))
        n=rd.pop(key)
        rn.extend([n])
    # ~~~ここまで~~~
#     rn
    etime=t.tocvalue()
    verifyT.extend([etime])
    verifyD.extend([rn])
    
# t.toc() #Time elapsed since t.tic()
print('{:.5f}[ms]'.format(np.mean(verifyT)*1000))

0.02791[ms]


In [1146]:
# vector based cosine_similarity function

cosine_similarity=lambda M1,M2:  np.dot(M1,M2.T)/(np.tile(np.array([np.linalg.norm(M1,axis=1)]).T,[1,len(M2)])*np.tile(np.linalg.norm(M2,axis=1),[len(M1),1]))

In [1147]:
verifyD_NP=np.array(verifyD)
csVec=cosine_similarity(verifyD_NP,verifyD_NP)
csVec2=csVec-np.eye(len(csVec))
list(csVec2.flat)

csVec2int=np.round(np.array(csVec.flat)*10)
countL = collections.Counter(csVec2int)
display(countL)
rankList=countL.most_common()
print(rankList)

Counter({10.0: 5220,
         5.0: 72872,
         9.0: 84330,
         6.0: 232954,
         7.0: 353452,
         8.0: 249716,
         4.0: 1456})

[(7.0, 353452), (8.0, 249716), (6.0, 232954), (9.0, 84330), (5.0, 72872), (10.0, 5220), (4.0, 1456)]


In [1130]:
np.round(np.array(csVec.flat)*10)

array([10.,  8.,  8.,  6., 10.,  7.,  9.,  7.,  8.,  9.,  8., 10.,  7.,
        7.,  7.,  9.,  8.,  8.,  8.,  8.,  8.,  7., 10.,  9.,  8.,  8.,
        9.,  8.,  7.,  9.,  6.,  7.,  9., 10.,  6.,  9.,  8.,  8.,  8.,
        7., 10.,  7.,  8.,  6., 10.,  7.,  9.,  8.,  8.,  9.,  7.,  9.,
        8.,  9.,  7., 10.,  8.,  7.,  8.,  8.,  9.,  8.,  9.,  8.,  9.,
        8., 10.,  7.,  7.,  9.,  7.,  8.,  8.,  8.,  8.,  7.,  7., 10.,
        8.,  7.,  8.,  8.,  7.,  8.,  8.,  8.,  7.,  8., 10.,  8.,  9.,
        8.,  9.,  7.,  9.,  8.,  9.,  7.,  8., 10.])

In [1137]:
csVec2=csVec-np.eye(len(csVec))
# csVec2

In [1138]:
verifyD_NP=np.array(verifyD)
csVec=cosine_similarity(verifyD_NP,verifyD_NP)
csVec2=csVec-np.eye(len(csVec))
list(csVec2.flat)

csVec2int=np.round(np.array(csVec.flat)*10)
countL = collections.Counter(csVec2int)
display(countL)
rankList=countL.most_common()
print(rankList)

Counter({10.0: 12, 8.0: 40, 6.0: 4, 7.0: 24, 9.0: 20})

[(8.0, 40), (7.0, 24), (9.0, 20), (10.0, 12), (6.0, 4)]


In [1030]:
np.array(verifyD)

array([[4, 5, 7, 6, 9, 2, 8, 1, 3],
       [4, 3, 1, 7, 5, 8, 6, 2, 9],
       [6, 1, 9, 8, 3, 5, 4, 7, 2],
       [6, 4, 7, 2, 1, 9, 3, 8, 5],
       [4, 7, 6, 8, 9, 1, 5, 2, 3],
       [3, 2, 6, 5, 1, 9, 8, 4, 7],
       [1, 3, 9, 8, 6, 7, 5, 4, 2],
       [9, 8, 2, 7, 1, 5, 4, 6, 3],
       [1, 9, 4, 6, 3, 2, 5, 7, 8],
       [3, 2, 6, 8, 5, 1, 9, 7, 4]])

In [1032]:
verifyD_NP=np.array(verifyD)

In [1057]:
verifyD_NP=numpy.random.rand(3,5)
verifyD_NP

array([[0.82699688, 0.31178071, 0.9542074 , 0.12212542, 0.60177326],
       [0.5215083 , 0.75296476, 0.90302125, 0.98384758, 0.58769801],
       [0.55196041, 0.5111711 , 0.77844217, 0.99133505, 0.00948876]])

In [1058]:
np.dot(verifyD_NP,verifyD_NP.T) 

array([[2.06868848, 2.00152893, 1.48541539],
       [2.00152893, 2.96771924, 2.35659471],
       [1.48541539, 2.35659471, 2.15476363]])

In [1059]:
verifyD_NP

array([[0.82699688, 0.31178071, 0.9542074 , 0.12212542, 0.60177326],
       [0.5215083 , 0.75296476, 0.90302125, 0.98384758, 0.58769801],
       [0.55196041, 0.5111711 , 0.77844217, 0.99133505, 0.00948876]])

In [1060]:
vlen=np.linalg.norm(verifyD_NP,axis=1)
vlen

array([1.4382936 , 1.72270695, 1.46791131])

In [1061]:
np.tile(vlen,[len(vlen),1])

array([[1.4382936 , 1.72270695, 1.46791131],
       [1.4382936 , 1.72270695, 1.46791131],
       [1.4382936 , 1.72270695, 1.46791131]])

In [1062]:
np.tile(np.array([vlen]).T,[1,len(vlen)])

array([[1.4382936 , 1.4382936 , 1.4382936 ],
       [1.72270695, 1.72270695, 1.72270695],
       [1.46791131, 1.46791131, 1.46791131]])

In [1038]:
np.shape(np.tile(vlen,[1,len(vlen)]))

(1, 100)

In [1039]:
np.shape(np.tile(vlen,[len(vlen),1]))

(10, 10)

In [1046]:
np.shape(np.tile(np.array([vlen]).T,[1,len(vlen)]))

(10, 10)

In [ ]:
np.tile(vlen,[len(vlen),1]),np.tile(np.array([vlen]).T,[1,len(vlen)])

In [1072]:
np.dot(verifyD_NP,verifyD_NP.T)/(np.tile(vlen,[len(vlen),1])*np.tile(np.array([vlen]).T,[1,len(vlen)]))

array([[1.        , 0.80779827, 0.70355905],
       [0.80779827, 1.        , 0.93190936],
       [0.70355905, 0.93190936, 1.        ]])

In [1121]:
# vector based cosine_similarity function

cosine_similarity=lambda M1,M2:  np.dot(M1,M2.T)/(np.tile(np.array([np.linalg.norm(M1,axis=1)]).T,[1,len(M2)])*np.tile(np.linalg.norm(M2,axis=1),[len(M1),1]))

In [1122]:
cosine_similarity(verifyD_NP[0:2],verifyD_NP[0:4])

array([[1.        , 0.80779827, 0.70355905],
       [0.80779827, 1.        , 0.93190936]])

In [1110]:
M1=numpy.random.rand(5,3)
M2=numpy.random.rand(7,3)
np.dot(M1,M2.T)
np.shape(np.dot(M1,M2.T))

(5, 7)

In [1111]:
M1

array([[0.84384199, 0.8009228 , 0.39257249],
       [0.79031776, 0.98292382, 0.43767086],
       [0.29220044, 0.24592503, 0.58232287],
       [0.55213454, 0.45078574, 0.81440339],
       [0.66462433, 0.26148302, 0.09057613]])

In [1112]:
numpy.random.rand(2,3)

array([[0.02421194, 0.00181157, 0.06451722],
       [0.9671518 , 0.41938832, 0.07708402]])

In [1083]:
M1

array([[0.82699688, 0.31178071, 0.9542074 , 0.12212542, 0.60177326],
       [0.5215083 , 0.75296476, 0.90302125, 0.98384758, 0.58769801]])

In [1093]:
np.linalg.norm(M1,axis=1)

array([1.4382936 , 1.72270695])

In [1113]:
np.tile(np.array([np.linalg.norm(M1,axis=1)]).T,[1,len(M2)])

array([[1.22786799, 1.22786799, 1.22786799, 1.22786799, 1.22786799,
        1.22786799, 1.22786799],
       [1.33502703, 1.33502703, 1.33502703, 1.33502703, 1.33502703,
        1.33502703, 1.33502703],
       [0.6963908 , 0.6963908 , 0.6963908 , 0.6963908 , 0.6963908 ,
        0.6963908 , 0.6963908 ],
       [1.08227224, 1.08227224, 1.08227224, 1.08227224, 1.08227224,
        1.08227224, 1.08227224],
       [0.71993257, 0.71993257, 0.71993257, 0.71993257, 0.71993257,
        0.71993257, 0.71993257]])

In [1114]:
np.shape(np.tile(np.array([np.linalg.norm(M1,axis=1)]).T,[1,len(M2)]))

(5, 7)

In [1116]:
np.tile(np.linalg.norm(M2,axis=1),[len(M1),1])

array([[1.321208  , 1.34957838, 1.09042003, 0.88291171, 0.7096706 ,
        1.09861332, 1.05258783],
       [1.321208  , 1.34957838, 1.09042003, 0.88291171, 0.7096706 ,
        1.09861332, 1.05258783],
       [1.321208  , 1.34957838, 1.09042003, 0.88291171, 0.7096706 ,
        1.09861332, 1.05258783],
       [1.321208  , 1.34957838, 1.09042003, 0.88291171, 0.7096706 ,
        1.09861332, 1.05258783],
       [1.321208  , 1.34957838, 1.09042003, 0.88291171, 0.7096706 ,
        1.09861332, 1.05258783]])

In [1117]:
np.shape(np.tile(np.linalg.norm(M2,axis=1),[len(M1),1]))

(5, 7)

In [1120]:
np.dot(M1,M2.T)/(np.tile(np.array([np.linalg.norm(M1,axis=1)]).T,[1,len(M2)])*np.tile(np.linalg.norm(M2,axis=1),[len(M1),1]))

array([[0.83671428, 0.83934186, 0.80948807, 0.74398869, 0.834386  ,
        0.98210825, 0.94056478],
       [0.78836219, 0.87849256, 0.81909335, 0.82281543, 0.84002848,
        0.98859937, 0.9741625 ],
       [0.92156765, 0.91847464, 0.99322973, 0.59881047, 0.99316465,
        0.86726005, 0.80839492],
       [0.94519539, 0.92778753, 0.9876446 , 0.63843628, 0.99372775,
        0.92282888, 0.86081224],
       [0.82728134, 0.56819577, 0.6079513 , 0.42038219, 0.64641762,
        0.83018925, 0.71796446]])

In [1045]:
np.array([vlen]).T

array([[16.88194302],
       [16.88194302],
       [16.88194302],
       [16.88194302],
       [16.88194302],
       [16.88194302],
       [16.88194302],
       [16.88194302],
       [16.88194302],
       [16.88194302]])

In [1028]:
len(np.linalg.norm(verifyD_NP,axis=1))

1000

In [1016]:
cos_sim=lambda v1,v2: np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
cos_sim(verifyD[0:1],verifyD[1:2])

ValueError: shapes (1,9) and (1,9) not aligned: 9 (dim 1) != 1 (dim 0)

In [ ]:
return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

In [1011]:
from pytictoc import TicToc
t = TicToc() #create instance of class
# t.tic() #Start timer

verifyT=[] 
verifyD=[]    
for i in range(1000):
    t.tic()
    # ~~~受講生のアイディアをお借りしました ~~~
    rd =list(range(LofD))
    rn = []
    while len(rn) < TofD:
        key = np.random.randint(0,len(rd))
        n=rd.pop(key)
        rn.extend([n])
    # ~~~ここまで~~~
#     rn
    etime=t.tocvalue()
    verifyT.extend([etime])
    verifyD.extend([rn])
    
# t.toc() #Time elapsed since t.tic()
print('{:.5f}[ms]'.format(np.mean(verifyT)*1000))

0.02969[ms]


In [1191]:
while not all(np.hstack([np.sum(baseM,axis=0),np.sum(baseM,axis=1), \
                         np.sum(np.diag(baseM)),np.sum(np.diag(np.fliplr(baseM)))])==np.tile(15,8)):
    # ~~~受講生のアイディアをお借りしました ~~~
    rd = list(range(1,10))
    rn = []
    while len(rn) < TofD:
        key = np.random.randint(0,len(rd))
        n=rd.pop(key)
        rn.extend([n])
    # ~~~ここまで~~~

    baseM=np.reshape(rn, (3, 3))

baseM    

array([[4, 9, 2],
       [3, 5, 7],
       [8, 1, 6]])

In [1189]:
# statistical analysis 3: 9! = 362880

from pytictoc import TicToc
t = TicToc() #create instance of class
t.tic() #Start timer

baseM=np.full((3,3),0)
LofD=9
TofD=9
    
verifyD=[]    
for verifyL in range(1000):
    loopN=0
    while not all(np.hstack([np.sum(baseM,axis=0),np.sum(baseM,axis=1),np.sum(np.diag(baseM)),np.sum(np.diag(np.fliplr(baseM)))])==np.tile(15,8)):
        # ~~~受講生のアイディアをお借りしました ~~~
        rd = list(range(1,10))
        rn = []
        while len(rn) < TofD:
            key = np.random.randint(0,len(rd))
            n=rd.pop(key)
            rn.extend([n])
        # ~~~ここまで~~~

#         baseM=np.array([[8, 1, 6],[3, 5, 7],[4, 9, 2]])
        baseM=np.reshape(rn, (3, 3))
   
        loopN=loopN+1
        verifyD.extend([loopN])

# display(baseM)
# display(rn)
# display(loopN)

print(np.mean(verifyD))
t.toc() #Time elapsed since t.tic()
etime=t.tocvalue()
display(etime/3600)
display(baseM)


35275.0
Elapsed time is 3.670909 seconds.


0.0010197069908301475

array([[4, 9, 2],
       [3, 5, 7],
       [8, 1, 6]])

In [979]:
t.toc() #Time elapsed since t.tic()
etime=t.tocvalue()
display(etime/3600)
display(baseM)


Elapsed time is 17037.956376 seconds.


4.732765999583337

array([[0, 5, 3],
       [8, 1, 6],
       [4, 7, 2]])

In [1188]:
# statistical analysis 3: 9! = 362880 (new2)

from pytictoc import TicToc
t = TicToc() #create instance of class
t.tic() #Start timer

baseM=np.full((3,3),0)
LofD=9
TofD=9
    
verifyD=[]    
for verifyL in range(1000):
    loopN=0
    while not all(np.hstack([np.sum(baseM,axis=0),np.sum(baseM,axis=1),np.sum(np.diag(baseM)),np.sum(np.diag(np.fliplr(baseM)))])==np.tile(15,8)):
        # ~~~受講生のアイディアをお借りしました ~~~
        baseM = np.zeros((3, 3), dtype=int)
        rn = np.random.choice(range(1, 10), size=9, replace=False)
        baseM.flat = rn
#         # ~~~ここまで~~~
        
#         baseM=np.array([[8, 1, 6],[3, 5, 7],[4, 9, 2]])
   
        loopN=loopN+1
        verifyD.extend([loopN])

# display(baseM)
# display(rn)
# display(loopN)

print(np.mean(verifyD))
t.toc() #Time elapsed since t.tic()
etime=t.tocvalue()
display(etime/3600)
display(baseM)

42715.5
Elapsed time is 3.369578 seconds.


0.0009360040855568109

array([[2, 9, 4],
       [7, 5, 3],
       [6, 1, 8]])

In [972]:
# verifyD.extend([loopN])
verifyD

[]

In [960]:
t.toc() #Time elapsed since t.tic()
etime=t.tocvalue()
display(etime/3600)

Elapsed time is 1969.624236 seconds.


0.5471180220138842

In [637]:
display(4*3*2*1*2*2*2*2)
display(4*3*2*1*2*2*2*2/2)

576

288.0

In [612]:
list(range(1,LofD))

[1, 2, 3]

In [561]:
8*7*6*5

1680

In [1259]:
4*3*2*1*2*2*2*2

384

In [564]:
sVecFull[rn[k]]

[1, 5, 9]

In [567]:
[1,3,4][::-1]

[4, 3, 1]

In [608]:
bool(np.random.randint(2))

False

In [559]:
all(np.hstack([np.sum(baseM,axis=0)[[0,2]],np.sum(baseM,axis=1)[[0,2]]])==np.tile(15,4))


True

In [560]:
len(sVecFull)

8

In [385]:
rn

[3, 1, 4, 2]

In [295]:
rd =list(range(1,5))
rn = []
while len(rn) < 4:
    key = np.random.randint(0,len(rd))
    print(key)
    n=rd.pop(key)
    rn.extend([n])
rn

3
2
1
0


[4, 3, 2, 1]

In [200]:
np.tile(15,4)

array([15, 15, 15, 15])

In [132]:
list(range(9,0,-1))

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [97]:
a=(np.where(tmpL+i+j==15))[0]
print(tmpL[a])

[0]


In [98]:
tmpL[np.where(tmpL+i+j==15)]

array([0])

In [35]:
for i in range(9,6,-1):
    
    for j in range(i-1,0,-1):
        print(j)
    print('-')

8
7
6
5
4
3
2
1
-
7
6
5
4
3
2
1
-
6
5
4
3
2
1
-


## Example 3

In [734]:
L1=[]
print('変数の状態(処理前): {0}'.format(L1))

L2=L1.append('a1') # 破壊的メソッド / 出力なし
print('出力: {0}'.format(L2))
print('変数の状態(処理後　１回目): {0}'.format(L1))
print('---')

L2=L1.append('a2') # 破壊的メソッド / 出力なし
print('出力: {0}'.format(L2))
print('変数の状態(処理後　2回目): {0}'.format(L1))

変数の状態(処理前): []
出力: None
変数の状態(処理後　１回目): ['a1']
---
出力: None
変数の状態(処理後　2回目): ['a1', 'a2']


In [736]:
listD = [10, 2,3,1]
print('変数の状態(処理前): {0}'.format(listD))

listD2=listD.sort()  # 破壊的メソッド / 出力なし
print('出力: {0}'.format(listD2))
print('変数の状態(処理後): {0}'.format(listD))

変数の状態(処理前): [10, 2, 3, 1]
出力: None
変数の状態(処理後): [1, 2, 3, 10]


In [737]:
listD = [10, 2,3,1]
print('変数の状態(処理前): {0}'.format(listD))

listD2=sorted(listD)  # 非破壊関数 / 出力あり
print('出力: {0}'.format(listD2))
print('変数の状態(処理後): {0}'.format(listD))

変数の状態(処理前): [10, 2, 3, 1]
出力: [1, 2, 3, 10]
変数の状態(処理後): [10, 2, 3, 1]


In [739]:
message1 = 'Hello'
print('変数の状態(処理前): {0}'.format(message1))

message2 = message1.replace('Hello', 'こんにちは') # 非破壊的メソッド / 出力あり
print('出力: {0}'.format(message2))
print('変数の状態(処理後): {0}'.format(message1))

変数の状態(処理前): Hello
出力: こんにちは
変数の状態(処理後): Hello


In [744]:
listD_NP=np.array( [10, 2,3,1])
display(listD_NP)
print('変数の状態(処理前):')
display(listD_NP)
print('---')
listD=listD_NP.tolist() # 非破壊的メソッド / 出力あり
print('出力:')
display(listD)
print('変数の状態(処理後)')
display(listD_NP)

array([10,  2,  3,  1])

変数の状態(処理前):


array([10,  2,  3,  1])

---
出力:


[10, 2, 3, 1]

変数の状態(処理後)


array([10,  2,  3,  1])

In [785]:
listD = [1,2,3,4,5,6]
print('変数の状態(処理前): {0}'.format(listD))
listD2=listD.pop(3) # 破壊的メソッド / 出力あり
print('出力: {0}'.format(listD2))
print('変数の状態(処理後　１回目): {0}'.format(listD))

print('---')
listD2=listD.pop(3) # 破壊的メソッド / 出力あり
print('出力: {0}'.format(listD2))
print('変数の状態(処理後　2回目): {0}'.format(listD))

変数の状態(処理前): [1, 2, 3, 4, 5, 6]
出力: 4
変数の状態(処理後　１回目): [1, 2, 3, 5, 6]
---
出力: 5
変数の状態(処理後　2回目): [1, 2, 3, 6]


## ----------------- Summary-----------------

In [925]:
import numpy as np
magic_square = [[0 for _ in range(3)] for _ in range(3)]
numbers = list(range(1,10))

for row in range(3):
    for col in range(3):
        idx = np.random.randint(0,len(numbers))
        magic_square[row][col] = numbers[idx]
        numbers.pop(idx)

display(magic_square)
magic_square_array = np.array(magic_square)
display(magic_square_array)

col_sum=magic_square_array.sum(axis=0)
display(col_sum)
row_sum=magic_square_array.sum(axis=1)
display(row_sum)

RSD=0
RR=0
for idx in range(len(C_np)):
    RSD=RSD+C_np[0:,idx:idx+1][idx]
    RR=RR+C_np[0:,idx:idx+1][len(C_np)-idx-1]
display(RSD)
display(RR)


[[8, 3, 9], [1, 5, 7], [6, 4, 2]]

array([[8, 3, 9],
       [1, 5, 7],
       [6, 4, 2]])

array([15, 12, 18])

array([20, 13, 12])

NameError: name 'C_np' is not defined

## ----------------- Hints-----------------

In [794]:
# ~~~~受講生のアイディア（コードDとします）~~~~~

rd = list(range(1,10))
rn = []
print('変数の状態(処理前): {0}'.format(rd))
loopN=0
while len(rn) < 9:
    key = np.random.randint(0,len(rd))
    n=rd.pop(key)
    rn.extend([n])
    loopN=loopN+1
    print('出力 n= {0}'.format(n))
    print('変数の状態(処理後　{0}回目) rd:{1}, rn:{2}'.format(loopN,rd,rn))

変数の状態(処理前): [1, 2, 3, 4, 5, 6, 7, 8, 9]
出力 n= 1
変数の状態(処理後　1回目) rd:[2, 3, 4, 5, 6, 7, 8, 9], rn:[1]
出力 n= 6
変数の状態(処理後　2回目) rd:[2, 3, 4, 5, 7, 8, 9], rn:[1, 6]
出力 n= 7
変数の状態(処理後　3回目) rd:[2, 3, 4, 5, 8, 9], rn:[1, 6, 7]
出力 n= 3
変数の状態(処理後　4回目) rd:[2, 4, 5, 8, 9], rn:[1, 6, 7, 3]
出力 n= 5
変数の状態(処理後　5回目) rd:[2, 4, 8, 9], rn:[1, 6, 7, 3, 5]
出力 n= 4
変数の状態(処理後　6回目) rd:[2, 8, 9], rn:[1, 6, 7, 3, 5, 4]
出力 n= 9
変数の状態(処理後　7回目) rd:[2, 8], rn:[1, 6, 7, 3, 5, 4, 9]
出力 n= 2
変数の状態(処理後　8回目) rd:[8], rn:[1, 6, 7, 3, 5, 4, 9, 2]
出力 n= 8
変数の状態(処理後　9回目) rd:[], rn:[1, 6, 7, 3, 5, 4, 9, 2, 8]


In [981]:
import numpy as np

def generate_magic_square():
    k=1
    while True:
        matrix = np.zeros((3, 3), dtype=int)
        numbers = np.random.choice(range(1, 10), size=9, replace=False)
        matrix.flat = numbers

        row_sums = np.sum(matrix, axis=1)
        col_sums = np.sum(matrix, axis=0)
        diag_sum1 = np.sum(np.diag(matrix))
        diag_sum2 = np.sum(np.diag(np.fliplr(matrix)))
        k=k+1
        magic_sum = row_sums[0]
        if np.all(row_sums == magic_sum) and np.all(col_sums == magic_sum) and \
           diag_sum1 == magic_sum and diag_sum2 == magic_sum:
            break
    print(k)
    return matrix

magic_square = generate_magic_square()

print("生成された魔法陣:")
print(magic_square)

5543
生成された魔法陣:
[[8 1 6]
 [3 5 7]
 [4 9 2]]


In [985]:
k=1
while True:
    matrix = np.zeros((3, 3), dtype=int)
    numbers = np.random.choice(range(1, 10), size=9, replace=False)
    matrix.flat = numbers

    row_sums = np.sum(matrix, axis=1)
    col_sums = np.sum(matrix, axis=0)
    diag_sum1 = np.sum(np.diag(matrix))
    diag_sum2 = np.sum(np.diag(np.fliplr(matrix)))
    k=k+1
    magic_sum = row_sums[0]
    if np.all(row_sums == magic_sum) and np.all(col_sums == magic_sum) and \
       diag_sum1 == magic_sum and diag_sum2 == magic_sum:
        break
print(k)
display(matrix)
# return matrix

29960


array([[4, 3, 8],
       [9, 5, 1],
       [2, 7, 6]])

In [1194]:
# 受講生の解答例
while True:
    matrix = np.zeros((3, 3), dtype=int)
    numbers = np.random.choice(range(1, 10), size=9, replace=False)
    matrix.flat = numbers

    row_sums = np.sum(matrix, axis=1)
    col_sums = np.sum(matrix, axis=0)
    diag_sum1 = np.sum(np.diag(matrix))
    diag_sum2 = np.sum(np.diag(np.fliplr(matrix)))

    magic_sum = row_sums[0]
    if np.all(row_sums == magic_sum) and np.all(col_sums == magic_sum) and \
       diag_sum1 == magic_sum and diag_sum2 == magic_sum:
        break

matrix

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

In [1196]:
row_sums[0]

15

In [1150]:
# 受講生の解答例
rd = list(range(1,10))
rn = []
while len(rn) < 9:
    key = np.random.randint(0,len(rd))
    n=rd.pop(key)
    rn.extend([n])

print(rn)

[9, 4, 6, 2, 8, 5, 7, 1, 3]


In [1201]:
a_np=np.array([[11,12,13],[21,22,23],[31,32,33]])
list(a_np.flat)

[11, 12, 13, 21, 22, 23, 31, 32, 33]

In [1202]:
a_np=np.arange(1, 10).reshape(3, 3)
display(a_np)f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1222]:
a_np=np.arange(1, 9).reshape(2, 4)
display(a_np)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [1221]:
a_np=np.arange(2**2*3).reshape(3,2,2)
display(a_np)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [1211]:
np.arange(1, 4*2)

array([1, 2, 3, 4, 5, 6, 7])

In [1213]:
2**4

16

In [1225]:
a_np=np.arange(1, 10).reshape(3, 3)
display(a_np)
display(np.fliplr(a_np))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [1228]:
a_np=np.arange(1, 10).reshape(3, 3)
display(a_np)
display(np.flipud(a_np))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [1231]:
display(np.diag(a_np))
display(np.diag(np.fliplr(a_np)))

array([1, 5, 9])

array([3, 5, 7])

In [1240]:
display(np.eye(len(a_np)))
display(np.eye(len(a_np))*np.diag(a_np))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [1238]:
np.eye(len(a_np))*np.diag(a_np)

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [1248]:
all([False,False]),all([True,False]),all([True,True])

(False, False, True)

In [1249]:
any([False,False]),any([True,False]),any([True,True])

(False, True, True)

In [1247]:
not any([False,False]),not any([True,False]),not any([True,True])

(True, False, False)

In [1254]:
np.diff(np.hstack([np.sum(baseM,axis=0),np.sum(baseM,axis=1), 
np.sum(np.diag(baseM)),np.sum(np.diag(np.fliplr(baseM)))]))

array([0, 0, 0, 0, 0, 0, 0])

In [1253]:
np.sum(np.diff(np.hstack([np.sum(baseM,axis=0),np.sum(baseM,axis=1), 
np.sum(np.diag(baseM)),np.sum(np.diag(np.fliplr(baseM)))])))

0

In [1256]:
bool(np.sum(np.diff(np.hstack([np.sum(baseM,axis=0),np.sum(baseM,axis=1), 
np.sum(np.diag(baseM)),np.sum(np.diag(np.fliplr(baseM)))]))))

False

In [1257]:
bool(0)

False