In [9]:
## Python basics for novice data scientists, supported by Wagatsuma Lab@Kyutech 
#
# The MIT License (MIT): Copyright (c) 2020 Hiroaki Wagatsuma and Wagatsuma Lab@Kyutech
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */
#
# # @Time    : 2023-7-1 
# # @Author  : Hiroaki Wagatsuma
# # @Site    : https://github.com/hirowgit/2A_python_basic_course
# # @IDE     : Python 3.10.9 (main, Dec 15 2022, 18:18:30) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
# # @File    : ksp_novice_lec02.py 

In [10]:
import numpy as np
import numpy.matlib
import os
import sys
import codecs
import matplotlib.pyplot as plt
import pandas as pd
from openpyxl import Workbook
import pprint
import datetime

## Example 1

In [11]:
sd1=pd.Series([10,20,30,40])
display(sd1)

0    10
1    20
2    30
3    40
dtype: int64

In [12]:
df1=pd.DataFrame([[10,'a',True],[20,'b',False,],[30,'c',False],[40,'d',True]])
display(df1)

0  1      2
0  10  a   True
1  20  b  False
2  30  c  False
3  40  d   True

## Example 2

In [13]:
df_utf=pd.read_csv('dataH/2023health_out.csv',encoding='utf8')
display(df_utf)

date  steps  kcal
0    2023/4/1   1166    35
1    2023/4/2  12746   382
2    2023/4/3   7911   237
3    2023/4/4   4390   132
4    2023/4/5  13479   404
5    2023/4/6   5667   170
6    2023/4/7   1677    50
7    2023/4/8  13287   399
8    2023/4/9   2633    79
9   2023/4/10   3464   104
10  2023/4/11  12350   371
11  2023/4/12   1401    42
12  2023/4/13  10677   320
13  2023/4/14   8522   256
14  2023/4/15   5192   156
15  2023/4/16   3685   111
16  2023/4/17  13648   409
17  2023/4/18   5943   178
18  2023/4/19  14510   435
19  2023/4/20  12420   373
20  2023/4/21  14918   448
21  2023/4/22   1509    45
22  2023/4/23  12737   382
23  2023/4/24  13949   418
24  2023/4/25   7063   212
25  2023/4/26   6050   182
26  2023/4/27  12808   384
27  2023/4/28   8753   263
28  2023/4/29  10898   327
29  2023/4/30    105     3

In [14]:
df_utf['date'].head(1)

0    2023/4/1
Name: date, dtype: object

In [15]:
d_conv=df_utf['date'].apply(pd.to_datetime)
d_conv[0]

Timestamp('2023-04-01 00:00:00')

In [18]:
d1=df_utf['date']
d1[0],d1[1]
# d1[1]-d1[0]


('2023/4/1', '2023/4/2')

In [21]:
d_conv=df_utf['date'].apply(pd.to_datetime)
d_conv[0],d_conv[1]
# d_conv[1]-d_conv[0]

Timedelta('1 days 00:00:00')

In [22]:
df_utf.loc[:,'date']=df_utf.loc[:,'date'].apply(pd.to_datetime)

In [23]:
df_utf.loc[:,'date']

0    2023-04-01
1    2023-04-02
2    2023-04-03
3    2023-04-04
4    2023-04-05
5    2023-04-06
6    2023-04-07
7    2023-04-08
8    2023-04-09
9    2023-04-10
10   2023-04-11
11   2023-04-12
12   2023-04-13
13   2023-04-14
14   2023-04-15
15   2023-04-16
16   2023-04-17
17   2023-04-18
18   2023-04-19
19   2023-04-20
20   2023-04-21
21   2023-04-22
22   2023-04-23
23   2023-04-24
24   2023-04-25
25   2023-04-26
26   2023-04-27
27   2023-04-28
28   2023-04-29
29   2023-04-30
Name: date, dtype: datetime64[ns]

In [16]:
df_utf.sort_values(by='steps')

date  steps  kcal
29 2023-04-30    105     3
0  2023-04-01   1166    35
11 2023-04-12   1401    42
21 2023-04-22   1509    45
6  2023-04-07   1677    50
8  2023-04-09   2633    79
9  2023-04-10   3464   104
15 2023-04-16   3685   111
3  2023-04-04   4390   132
14 2023-04-15   5192   156
5  2023-04-06   5667   170
17 2023-04-18   5943   178
25 2023-04-26   6050   182
24 2023-04-25   7063   212
2  2023-04-03   7911   237
13 2023-04-14   8522   256
27 2023-04-28   8753   263
12 2023-04-13  10677   320
28 2023-04-29  10898   327
10 2023-04-11  12350   371
19 2023-04-20  12420   373
22 2023-04-23  12737   382
1  2023-04-02  12746   382
26 2023-04-27  12808   384
7  2023-04-08  13287   399
4  2023-04-05  13479   404
16 2023-04-17  13648   409
23 2023-04-24  13949   418
18 2023-04-19  14510   435
20 2023-04-21  14918   448

In [9]:
df_utf.sort_values(by='steps',ascending=False).head(3)

date  steps  kcal
20 2023-04-21  14918   448
18 2023-04-19  14510   435
23 2023-04-24  13949   418

## Example 3

In [27]:
df_part=df_utf[['steps','kcal']]
# df_utf['kcal']
display(df_part)
dataNP=df_part.to_numpy()
key=np.where(dataNP[:,1]>200)[0]

keyDf=df_part.iloc[key,:]
keyDf_ori=df_utf.iloc[key,:]
keyDf_date=df_utf.iloc[key,0]

display(keyDf)
display(keyDf_ori)
display(keyDf_date)

steps  kcal
0    1166    35
1   12746   382
2    7911   237
3    4390   132
4   13479   404
5    5667   170
6    1677    50
7   13287   399
8    2633    79
9    3464   104
10  12350   371
11   1401    42
12  10677   320
13   8522   256
14   5192   156
15   3685   111
16  13648   409
17   5943   178
18  14510   435
19  12420   373
20  14918   448
21   1509    45
22  12737   382
23  13949   418
24   7063   212
25   6050   182
26  12808   384
27   8753   263
28  10898   327
29    105     3

steps  kcal
1   12746   382
2    7911   237
4   13479   404
7   13287   399
10  12350   371
12  10677   320
13   8522   256
16  13648   409
18  14510   435
19  12420   373
20  14918   448
22  12737   382
23  13949   418
24   7063   212
26  12808   384
27   8753   263
28  10898   327

date  steps  kcal
1  2023-04-02  12746   382
2  2023-04-03   7911   237
4  2023-04-05  13479   404
7  2023-04-08  13287   399
10 2023-04-11  12350   371
12 2023-04-13  10677   320
13 2023-04-14   8522   256
16 2023-04-17  13648   409
18 2023-04-19  14510   435
19 2023-04-20  12420   373
20 2023-04-21  14918   448
22 2023-04-23  12737   382
23 2023-04-24  13949   418
24 2023-04-25   7063   212
26 2023-04-27  12808   384
27 2023-04-28   8753   263
28 2023-04-29  10898   327

1    2023-04-02
2    2023-04-03
4    2023-04-05
7    2023-04-08
10   2023-04-11
12   2023-04-13
13   2023-04-14
16   2023-04-17
18   2023-04-19
19   2023-04-20
20   2023-04-21
22   2023-04-23
23   2023-04-24
24   2023-04-25
26   2023-04-27
27   2023-04-28
28   2023-04-29
Name: date, dtype: datetime64[ns]

## ----------------- Summary-----------------

In [79]:
fpath = os.path.join('dataH', '2023health_full_out.csv')
df_utf=pd.read_csv(fpath,encoding='utf8')
df_utf.loc[:,'date']=df_utf.loc[:,'date'].apply(pd.to_datetime)
display(df_utf)

date  steps  kcal
0   2023-04-01   1166    35
1   2023-04-02  12746   382
2   2023-04-03   7911   237
3   2023-04-04   4390   132
4   2023-04-05  13479   404
..         ...    ...   ...
361 2023-03-27   5121   154
362 2023-03-28    485    15
363 2023-03-29   7686   231
364 2023-03-30  10844   325
365 2023-03-31   4702   141

[366 rows x 3 columns]

In [103]:
d_NP=df_utf.iloc[:,0].to_numpy()
a=d_NP.astype('datetime64[D]')
# d_NP[0].month
a[0]
d_NP.astype('datetime64[D]')

array(['2023-04-01', '2023-04-02', '2023-04-03', '2023-04-04',
       '2023-04-05', '2023-04-06', '2023-04-07', '2023-04-08',
       '2023-04-09', '2023-04-10', '2023-04-11', '2023-04-12',
       '2023-04-13', '2023-04-14', '2023-04-15', '2023-04-16',
       '2023-04-17', '2023-04-18', '2023-04-19', '2023-04-20',
       '2023-04-21', '2023-04-22', '2023-04-23', '2023-04-24',
       '2023-04-25', '2023-04-26', '2023-04-27', '2023-04-28',
       '2023-04-29', '2023-04-30', '2023-05-01', '2023-05-02',
       '2023-05-03', '2023-05-04', '2023-05-05', '2023-05-06',
       '2023-05-07', '2023-05-08', '2023-05-09', '2023-05-10',
       '2023-05-11', '2023-05-12', '2023-05-13', '2023-05-14',
       '2023-05-15', '2023-05-16', '2023-05-17', '2023-05-18',
       '2023-05-19', '2023-05-20', '2023-05-21', '2023-05-22',
       '2023-05-23', '2023-05-24', '2023-05-25', '2023-05-26',
       '2023-05-27', '2023-05-28', '2023-05-29', '2023-05-30',
       '2023-05-31', '2023-06-01', '2023-06-02', '2023-

In [115]:
d_NP[0].astype('datetime64[D]')

numpy.datetime64('2023-04-01')

In [123]:
df_utf['date'].dt.month 

0      4
1      4
2      4
3      4
4      4
      ..
361    3
362    3
363    3
364    3
365    3
Name: date, Length: 366, dtype: int64

In [120]:
df_utf['date'].dt.month ==4

0       True
1       True
2       True
3       True
4       True
       ...  
361    False
362    False
363    False
364    False
365    False
Name: date, Length: 366, dtype: bool

In [129]:
# (df_utf['date'].dt.month ==4).to_numpy()

In [154]:
d_NP=df_utf['date'].to_numpy()
d64=d_NP.astype('datetime64[D]')
pd_d = pd.to_datetime(d64)
display(pd_d)
display(pd_d.month)

DatetimeIndex(['2023-04-01', '2023-04-02', '2023-04-03', '2023-04-04',
               '2023-04-05', '2023-04-06', '2023-04-07', '2023-04-08',
               '2023-04-09', '2023-04-10',
               ...
               '2023-03-22', '2023-03-23', '2023-03-24', '2023-03-25',
               '2023-03-26', '2023-03-27', '2023-03-28', '2023-03-29',
               '2023-03-30', '2023-03-31'],
              dtype='datetime64[ns]', length=366, freq=None)

Int64Index([4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
            ...
            3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
           dtype='int64', length=366)

In [156]:
d64[0]

numpy.datetime64('2023-04-01')

In [158]:
b=(str(a[0]).split('-'))
b

['2023', '04', '01']

In [159]:
b[0].astype(int)

AttributeError: 'str' object has no attribute 'astype'

In [164]:
np.array((str(d64).split('-')))
# np.array((str(d64).split('-'))).astype(int)

array(["['2023", '04', "01' '2023", '04', "02' '2023", '04', "03' '2023",
       '04', "04' '2023", '04', "05'\n '2023", '04', "06' '2023", '04',
       "07' '2023", '04', "08' '2023", '04', "09' '2023", '04',
       "10'\n '2023", '04', "11' '2023", '04', "12' '2023", '04',
       "13' '2023", '04', "14' '2023", '04', "15'\n '2023", '04',
       "16' '2023", '04', "17' '2023", '04', "18' '2023", '04',
       "19' '2023", '04', "20'\n '2023", '04', "21' '2023", '04',
       "22' '2023", '04', "23' '2023", '04', "24' '2023", '04',
       "25'\n '2023", '04', "26' '2023", '04', "27' '2023", '04',
       "28' '2023", '04', "29' '2023", '04', "30'\n '2023", '05',
       "01' '2023", '05', "02' '2023", '05', "03' '2023", '05',
       "04' '2023", '05', "05'\n '2023", '05', "06' '2023", '05',
       "07' '2023", '05', "08' '2023", '05', "09' '2023", '05',
       "10'\n '2023", '05', "11' '2023", '05', "12' '2023", '05',
       "13' '2023", '05', "14' '2023", '05', "15'\n '2023", '05',
      

In [137]:
import time

d_NP[0]

numpy.datetime64('2023-04-01T00:00:00.000000000')

In [105]:
# a[0].astype(datetime)
# a.astype(datetime)
	
a[0].astype('datetime64[D]').astype(datetime).strftime('%Y-%m-%d')


TypeError: Cannot interpret '<module 'datetime' from '/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/datetime.py'>' as a data type

In [95]:
a[0].strftime('%Y-%m-%d')


AttributeError: 'numpy.datetime64' object has no attribute 'strftime'

In [77]:
month_list=[d.month for d in df_utf['date']]
key=np.where(np.array(month_list)==4)[0]
df4=df_utf.iloc[key,:]

In [78]:
df4.to_csv('dataH/data_4.csv')

In [38]:
os.path.join("dataH", "2023health_"+month_list_FY[0]+".csv")

'dataH/2023health_April.csv'

In [41]:
for m in month_list_FY:
    fpath = os.path.join("dataH", "2023health_"+m+".csv")
    df_data=pd.read_csv(fpath,encoding="utf8")
    display("2023health_"+m+".csv")
    display(df_data)

'2023health_April.csv'

date  steps  kcal
0    2023/4/1  14886   447
1    2023/4/2   6893   207
2    2023/4/3   7711   231
3    2023/4/4   8399   252
4    2023/4/5  12150   365
5    2023/4/6   6165   185
6    2023/4/7  10913   327
7    2023/4/8  11316   339
8    2023/4/9   9871   296
9   2023/4/10  12274   368
10  2023/4/11   2845    85
11  2023/4/12     87     3
12  2023/4/13  14484   435
13  2023/4/14  14394   432
14  2023/4/15   1032    31
15  2023/4/16   4766   143
16  2023/4/17  12371   371
17  2023/4/18   1285    39
18  2023/4/19   1151    35
19  2023/4/20   6314   189
20  2023/4/21    152     5
21  2023/4/22  11130   334
22  2023/4/23   2215    66
23  2023/4/24  14541   436
24  2023/4/25   2350    71
25  2023/4/26   8367   251
26  2023/4/27    103     3
27  2023/4/28   2641    79
28  2023/4/29   1926    58
29  2023/4/30  10834   325

'2023health_May.csv'

date  steps  kcal
0    2023/5/1   2380    71
1    2023/5/2  12565   377
2    2023/5/3     32     1
3    2023/5/4  13075   392
4    2023/5/5  12069   362
5    2023/5/6  12440   373
6    2023/5/7   1054    32
7    2023/5/8  12803   384
8    2023/5/9   7781   233
9   2023/5/10   6564   197
10  2023/5/11    271     8
11  2023/5/12   9661   290
12  2023/5/13  12549   376
13  2023/5/14   8393   252
14  2023/5/15  10749   322
15  2023/5/16   5848   175
16  2023/5/17  11054   332
17  2023/5/18  10000   300
18  2023/5/19  10214   306
19  2023/5/20   6281   188
20  2023/5/21   9280   278
21  2023/5/22   7797   234
22  2023/5/23   3067    92
23  2023/5/24   1167    35
24  2023/5/25   1085    33
25  2023/5/26   5575   167
26  2023/5/27   4377   131
27  2023/5/28   4131   124
28  2023/5/29   6880   206
29  2023/5/30   2332    70
30  2023/5/31  11977   359

'2023health_June.csv'

date  steps  kcal
0    2023/6/1   3777   113
1    2023/6/2   8834   265
2    2023/6/3    243     7
3    2023/6/4   5581   167
4    2023/6/5    934    28
5    2023/6/6  11825   355
6    2023/6/7   3338   100
7    2023/6/8   5320   160
8    2023/6/9  10001   300
9   2023/6/10   5502   165
10  2023/6/11   2992    90
11  2023/6/12   3701   111
12  2023/6/13   4871   146
13  2023/6/14   5058   152
14  2023/6/15    856    26
15  2023/6/16   1265    38
16  2023/6/17   3001    90
17  2023/6/18  11403   342
18  2023/6/19  11689   351
19  2023/6/20   6641   199
20  2023/6/21   2887    87
21  2023/6/22   6808   204
22  2023/6/23   1685    51
23  2023/6/24   3315    99
24  2023/6/25  11023   331
25  2023/6/26  14584   438
26  2023/6/27  10176   305
27  2023/6/28   9829   295
28  2023/6/29  12846   385
29  2023/6/30   6047   181

'2023health_July.csv'

date  steps  kcal
0    2023/7/1   5759   173
1    2023/7/2   7841   235
2    2023/7/3    613    18
3    2023/7/4   4622   139
4    2023/7/5  11747   352
5    2023/7/6  10904   327
6    2023/7/7  14022   421
7    2023/7/8     59     2
8    2023/7/9   2273    68
9   2023/7/10   4516   135
10  2023/7/11   7884   237
11  2023/7/12  10563   317
12  2023/7/13  14056   422
13  2023/7/14   5188   156
14  2023/7/15   7907   237
15  2023/7/16   8791   264
16  2023/7/17   5302   159
17  2023/7/18   2469    74
18  2023/7/19   4566   137
19  2023/7/20   3635   109
20  2023/7/21  11525   346
21  2023/7/22  13166   395
22  2023/7/23   2976    89
23  2023/7/24   6842   205
24  2023/7/25   7360   221
25  2023/7/26    953    29
26  2023/7/27  12999   390
27  2023/7/28  13280   398
28  2023/7/29   9015   270
29  2023/7/30  10922   328
30  2023/7/31   8330   250

'2023health_August.csv'

date  steps  kcal
0    2023/8/1    511    15
1    2023/8/2     77     2
2    2023/8/3  12215   366
3    2023/8/4  14462   434
4    2023/8/5  10230   307
5    2023/8/6   1966    59
6    2023/8/7   8197   246
7    2023/8/8  11403   342
8    2023/8/9  12203   366
9   2023/8/10   4717   142
10  2023/8/11   1090    33
11  2023/8/12  10737   322
12  2023/8/13   9248   277
13  2023/8/14   5664   170
14  2023/8/15  11057   332
15  2023/8/16  14689   441
16  2023/8/17   1378    41
17  2023/8/18   8801   264
18  2023/8/19  10719   322
19  2023/8/20  10812   324
20  2023/8/21   5439   163
21  2023/8/22   7293   219
22  2023/8/23    431    13
23  2023/8/24  11387   342
24  2023/8/25   8997   270
25  2023/8/26  11104   333
26  2023/8/27  13032   391
27  2023/8/28    759    23
28  2023/8/29  12233   367
29  2023/8/30  13238   397
30  2023/8/31   4415   132

'2023health_September.csv'

date  steps  kcal
0    2023/9/1   6524   196
1    2023/9/2  10573   317
2    2023/9/3   8745   262
3    2023/9/4   2950    89
4    2023/9/5    603    18
5    2023/9/6  14420   433
6    2023/9/7   6253   188
7    2023/9/8   6577   197
8    2023/9/9   3847   115
9   2023/9/10  11774   353
10  2023/9/11  11945   358
11  2023/9/12  12774   383
12  2023/9/13   3130    94
13  2023/9/14   6413   192
14  2023/9/15    937    28
15  2023/9/16  14124   424
16  2023/9/17   4231   127
17  2023/9/18   7722   232
18  2023/9/19   9258   278
19  2023/9/20  12174   365
20  2023/9/21   4939   148
21  2023/9/22  10451   314
22  2023/9/23   8992   270
23  2023/9/24   2192    66
24  2023/9/25  12883   386
25  2023/9/26   7909   237
26  2023/9/27  11458   344
27  2023/9/28   7385   222
28  2023/9/29   9730   292
29  2023/9/30   8377   251

'2023health_October.csv'

date  steps  kcal
0    2023/10/1  10042   301
1    2023/10/2   2359    71
2    2023/10/3  12450   374
3    2023/10/4  13903   417
4    2023/10/5  12455   374
5    2023/10/6    193     6
6    2023/10/7   6013   180
7    2023/10/8   9595   288
8    2023/10/9  11429   343
9   2023/10/10  12284   369
10  2023/10/11   3359   101
11  2023/10/12  13063   392
12  2023/10/13    365    11
13  2023/10/14   4944   148
14  2023/10/15    835    25
15  2023/10/16   8677   260
16  2023/10/17   4961   149
17  2023/10/18  11476   344
18  2023/10/19   9788   294
19  2023/10/20   7814   234
20  2023/10/21  14091   423
21  2023/10/22   7402   222
22  2023/10/23   2036    61
23  2023/10/24  10172   305
24  2023/10/25  14196   426
25  2023/10/26   6269   188
26  2023/10/27  12648   379
27  2023/10/28    262     8
28  2023/10/29   4200   126
29  2023/10/30  10233   307
30  2023/10/31   2128    64

'2023health_November.csv'

date  steps  kcal
0    2023/11/1  13429   403
1    2023/11/2  12506   375
2    2023/11/3  14644   439
3    2023/11/4   4916   147
4    2023/11/5   2561    77
5    2023/11/6   4622   139
6    2023/11/7   4727   142
7    2023/11/8  13374   401
8    2023/11/9  12047   361
9   2023/11/10  12787   384
10  2023/11/11   3170    95
11  2023/11/12  12934   388
12  2023/11/13   2709    81
13  2023/11/14   8301   249
14  2023/11/15     30     1
15  2023/11/16   9862   296
16  2023/11/17   2959    89
17  2023/11/18    782    23
18  2023/11/19  10666   320
19  2023/11/20   4765   143
20  2023/11/21   7404   222
21  2023/11/22   1528    46
22  2023/11/23   3758   113
23  2023/11/24   4130   124
24  2023/11/25  10294   309
25  2023/11/26  12942   388
26  2023/11/27  11718   352
27  2023/11/28  14285   429
28  2023/11/29   2401    72
29  2023/11/30   8756   263

FileNotFoundError: [Errno 2] No such file or directory: 'dataH/2023health_January.csv'

In [36]:
month_list=[datetime.date(2023, k+1, 1).strftime("%B") for k in range(12)]
display(month_list)
month_list_FY=month_list[3:11]+month_list[0:2]
display(month_list_FY)


['January',
 'February',
 'March',
 'April',
 'May',
 'June',
 'July',
 'August',
 'September',
 'October',
 'November',
 'December']

['April',
 'May',
 'June',
 'July',
 'August',
 'September',
 'October',
 'November',
 'January',
 'February']

In [28]:
fpath = os.path.join("dataH", "2023health_April.csv")
df_data=pd.read_csv(fpath,encoding="utf8")
display(df_data)

date  steps  kcal
0    2023/4/1  14886   447
1    2023/4/2   6893   207
2    2023/4/3   7711   231
3    2023/4/4   8399   252
4    2023/4/5  12150   365
5    2023/4/6   6165   185
6    2023/4/7  10913   327
7    2023/4/8  11316   339
8    2023/4/9   9871   296
9   2023/4/10  12274   368
10  2023/4/11   2845    85
11  2023/4/12     87     3
12  2023/4/13  14484   435
13  2023/4/14  14394   432
14  2023/4/15   1032    31
15  2023/4/16   4766   143
16  2023/4/17  12371   371
17  2023/4/18   1285    39
18  2023/4/19   1151    35
19  2023/4/20   6314   189
20  2023/4/21    152     5
21  2023/4/22  11130   334
22  2023/4/23   2215    66
23  2023/4/24  14541   436
24  2023/4/25   2350    71
25  2023/4/26   8367   251
26  2023/4/27    103     3
27  2023/4/28   2641    79
28  2023/4/29   1926    58
29  2023/4/30  10834   325

## Example 3-1

In [ ]:
# データ連結　（月毎）⇒年

## Example 4

In [ ]:
# グラフプロット

## Example 5

In [16]:
## https://ja.wikipedia.org/wiki/トップレベルドメイン一覧

In [10]:
url="https://ja.wikipedia.org/wiki/%E3%83%88%E3%83%83%E3%83%97%E3%83%AC%E3%83%99%E3%83%AB%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3%E4%B8%80%E8%A6%A7"
tables=pd.read_html(url)


In [13]:
len(tables)

40

In [15]:
tables

[    0                                                  1
 0 NaN  この記事の一部（New TLDs: https://newgtlds.icann.org/e...,
    Name               Entity                     Administrator[6]  \
 0  .com       商用(commercial)                                ベリサイン   
 1  .org     団体(organization)        Public Interest Registry（英語版）   
 2  .net  ネットワークインフラ(network)                                ベリサイン   
 3  .int                 国際機関  Internet Assigned Numbers Authority   
 4  .edu      アメリカ合衆国内の高等教育機関              Educause（英語版）（ベリサインが代行)   
 5  .gov          アメリカ合衆国連邦政府          アメリカ合衆国一般調達局（英語版）（ベリサインが代行)   
 6  .mil         アメリカ合衆国の軍事機関                          アメリカ合衆国国防総省   
 
                                                Notes  IDN DNSSEC  
 0  一般に開かれたドメインである。どんな個人や団体でも登録することを許される。当初は営利目的の企...  Yes    Yes  
 1  一般に開かれたドメインである。どんな個人や団体でも登録することを許される。当初は非営利団体に...  Yes    Yes  
 2  一般に開かれたドメインである。どんな個人や団体でも登録することを許される。当初は、コンピュー...  Yes    Yes  
 3  .int ドメインは、2つ以上の国の間の条約によって設立された組織・機関・運動のみに利用が

In [20]:
df_t=tables[4]
display(df_t)

Name        Entity          Explanation  \
0    .ac       アセンション島                  NaN   
1    .ad          アンドラ                  NaN   
2    .ae      アラブ首長国連邦                  NaN   
3    .af       アフガニスタン                  NaN   
4    .ag  アンティグア・バーブーダ                  NaN   
..   ...           ...                  ...   
248  .ye          イエメン                  NaN   
249  .yt         マヨット島                  NaN   
250  .za         南アフリカ  Zuid-Afrika (オランダ語)   
251  .zm          ザンビア                  NaN   
252  .zw         ジンバブエ                  NaN   

                                                 Notes            IDN DNSSEC  \
0    広く学術的なサイト（大学など）のために用いられる。アセンション島はイギリス領であるが、イギリ...            Yes    Yes   
1                        アンドラにおける商標または市民権が必要となる[7][8]。            NaN    Yes   
2                                                  NaN            NaN     No   
3                                                  NaN            NaN    Yes   
4    AGがドイツの株式会社(Aktiengesellschaft)の略称であることから、非公式に...            NaN    Yes   
..                                                 ...            ...    ...   
248                                                NaN            NaN     No   
249  欧州連合・スイス・ノルウェー・アイスランド・リヒテンシュタインの個人・企業に限る[cctld...  Yes[cctld 12]    Yes   
250                                                NaN            NaN     No   
251                                                NaN            NaN    Yes   
252                                                NaN            NaN     No   

               SLD IPv6  
0              Yes  Yes  
1              Yes  NaN  
2              Yes  NaN  
3              Yes  NaN  
4              Yes  NaN  
..             ...  ...  
248             No  NaN  
249            Yes  NaN  
250             No  NaN  
251  Yes[cctld 28]  NaN  
252             No  NaN  

[253 rows x 8 columns]

In [21]:
df_t.to_csv("dataH/write_data_4.csv")

In [22]:
df_t.to_excel("dataH/write_data_4.xlsx")

## ----------------- Summary-----------------

In [46]:
index=np.random.randint(1, 10, (18,1))
score=np.random.randint(0, 100, (18,1))
B=np.hstack([index,score])
index_sum=np.sum(B[:,0])
score_sum=np.sum(B[:,1])

index1=np.where(index<5)[0]
value_less_than_five=score[index1]
sum_value1=np.sum(value_less_than_five)

index2=np.where(index>=5)[0]
value_five_or_more=score[index2]
sum_value2=np.sum(value_five_or_more)

sum_all=sum_value1+sum_value2

display(score_sum)
display(sum_all)

964

964

## ----------------- Hints-----------------

In [53]:
A=[[1,4,7],[2,5,8],[3,6,9]]
A_np=np.array(A)

In [52]:
A_np[0,0]+A_np[1,1]+A_np[2,2]

15

In [55]:
index3=np.where(index==5)[0]
display(index3)

array([ 6, 11])

In [58]:
for i in range(10):
    display(i+1)

1

2

3

4

5

6

7

8

9

10

In [1]:
import geoplotlib

ModuleNotFoundError: No module named 'geoplotlib'

In [2]:
import branca

ModuleNotFoundError: No module named 'branca'

In [3]:
import branca

In [84]:
df_utf.loc[:,'date']=df_utf.loc[:,'date'].apply(pd.to_datetime)
df_utf.loc[:,0]=df_utf.loc[:,'date'].apply(pd.to_datetime)
df_utf.loc[:,'date']

0     2023-04-01
1     2023-04-02
2     2023-04-03
3     2023-04-04
4     2023-04-05
         ...    
361   2023-03-27
362   2023-03-28
363   2023-03-29
364   2023-03-30
365   2023-03-31
Name: date, Length: 366, dtype: datetime64[ns]

In [165]:
pd.to_datetime('2023/4/1')

Timestamp('2023-04-01 00:00:00')

In [249]:
## store 1
NofDate=366
NofReq=100
productID=range(1000,2000)
NofPrdMax=50
fpath_order = os.path.join('dataH', '2023order.csv')


date_list=[datetime.datetime(2023, 4, 1)+datetime.timedelta(days=i) for i in range(NofDate)]
display(date_list[0])
display(date_list[-1])

NofDreq=np.random.randint(1,NofReq, (NofDate,1))

for k in range(NofDate):
    r=set()
    while len(r) < NofDreq[k]:
        k2=len(r)
        n = np.random.randint(1000,2000)
        r.add(n)
    dP=np.vstack([np.full(NofDreq[k],k),np.array(list(r)),np.random.randint(1,NofPrdMax,NofDreq[k])])
#     display(dP)
#     display(dP.T)
    if k==0:
        data_full=dP.T
    else:
         data_full=np.vstack([data_full,dP.T])
    
df_order=pd.DataFrame(data_full,columns=['date', 'productID', 'order'])
df_order['date']=df_order['date'].map(lambda x: date_list[x])
df_order.to_csv(fpath_order)

datetime.datetime(2023, 4, 1, 0, 0)

datetime.datetime(2024, 3, 31, 0, 0)

In [255]:
## store 100
NofDate=366
NofReq=100
productID=range(1000,2000)
NofPrdMax=50
fpath_orderM = os.path.join('dataH', '2023orderMstore.csv')


date_list=[datetime.datetime(2023, 4, 1)+datetime.timedelta(days=i) for i in range(NofDate)]
display(date_list[0])
display(date_list[-1])

NofDreq=np.random.randint(1,NofReq, (NofDate,1))

for k in range(NofDate):
    for j in range(20):
        r=set()
        while len(r) < NofDreq[k]:
            k2=len(r)
            n = np.random.randint(1000,2000)
            r.add(n)
        dP=np.vstack([np.full(NofDreq[k],k),np.full(NofDreq[k],j+1),np.array(list(r)),np.random.randint(1,NofPrdMax,NofDreq[k])])
    #     display(dP)
    #     display(dP.T)
        if (k==0) and (j==0) :
            data_full=dP.T
        else:
             data_full=np.vstack([data_full,dP.T])
    
df_order=pd.DataFrame(data_full,columns=['date','storeID', 'productID', 'order'])
df_order['date']=df_order['date'].map(lambda x: date_list[x])
df_order.to_csv(fpath_orderM,index=False)

datetime.datetime(2023, 4, 1, 0, 0)

datetime.datetime(2024, 3, 31, 0, 0)

In [248]:
# date_list[[0,1]]
# map(lambda x: date_list[x])
(lambda x: date_list[x])

<function __main__.<lambda>(x)>

In [241]:
df_order['date'].map(lambda x: date_list[x])

0       2023-04-01
1       2023-04-01
2       2023-04-01
3       2023-04-01
4       2023-04-01
           ...    
18526   2024-03-31
18527   2024-03-31
18528   2024-03-31
18529   2024-03-31
18530   2024-03-31
Name: date, Length: 18531, dtype: datetime64[ns]

In [231]:
df_order['date'].to_numpy()

array([  0,   0,   0, ..., 365, 365, 365])

In [236]:
date_list_NP=np.array(date_list)
# date_list_NP(df_order['date'][0])
# date_list_NP[0]
# apply(pd.to_datetime)
df_order['date'].map(date_list)

TypeError: 'list' object is not callable

In [216]:
k=3

NofPrdMax=10

r=set()
while len(r) < NofDreq[k]:
    k2=len(r)
    n = np.random.randint(1000,2000)
    r.add(n)
dP=np.vstack([np.full(NofDreq[k],k),np.array(list(r)),np.random.randint(1,NofPrdMax,NofDreq[k])])
display(dP)
display(dP.T)
# display(np.array(reqL))

array([[   3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
           3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
           3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
           3,    3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
           3,    3,    3,    3,    3],
       [1924, 1925, 1799, 1544, 1161, 1422, 1681, 1297, 1042, 1300, 1558,
        1304, 1822, 1055, 1953, 1570, 1192, 1706, 1707, 1841, 1459, 1972,
        1461, 1717, 1971, 1339, 1213, 1856, 1349, 1351, 1864, 1866, 1483,
        1361, 1233, 1236, 1496, 1113, 1371, 1246, 1119, 1515, 1644, 1518,
        1010, 1780, 1524, 1148, 1150],
       [   6,    8,    6,    9,    2,    2,    6,    6,    8,    8,    1,
           2,    2,    4,    3,    8,    9,    4,    5,    6,    6,    8,
           9,    2,    8,    7,    4,    5,    3,    8,    9,    1,    1,
           3,    3,    1,    3,    2,    9,    8,    1,    1,    8,    4,
           8,    8,    2,    2,   

array([[   3, 1924,    6],
       [   3, 1925,    8],
       [   3, 1799,    6],
       [   3, 1544,    9],
       [   3, 1161,    2],
       [   3, 1422,    2],
       [   3, 1681,    6],
       [   3, 1297,    6],
       [   3, 1042,    8],
       [   3, 1300,    8],
       [   3, 1558,    1],
       [   3, 1304,    2],
       [   3, 1822,    2],
       [   3, 1055,    4],
       [   3, 1953,    3],
       [   3, 1570,    8],
       [   3, 1192,    9],
       [   3, 1706,    4],
       [   3, 1707,    5],
       [   3, 1841,    6],
       [   3, 1459,    6],
       [   3, 1972,    8],
       [   3, 1461,    9],
       [   3, 1717,    2],
       [   3, 1971,    8],
       [   3, 1339,    7],
       [   3, 1213,    4],
       [   3, 1856,    5],
       [   3, 1349,    3],
       [   3, 1351,    8],
       [   3, 1864,    9],
       [   3, 1866,    1],
       [   3, 1483,    1],
       [   3, 1361,    3],
       [   3, 1233,    3],
       [   3, 1236,    1],
       [   3, 1496,    3],
 

In [212]:
len(np.random.randint(1,NofPrdMax,NofDreq[k]))

49

In [209]:
display(len(r))
display(len(reqL))
NofDreq[k]

49

52

array([49])

In [195]:
dP=np.random.randint(1,NofPrdMax,NofPrdMax)
dP

array([8, 5, 6, 9, 1, 3, 8, 7, 4, 8])

In [196]:
k=4
dN=np.full(NofPrdMax,4)
dN

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [179]:
productID=range(1000,2000)
productID[-1]

1999