In [ ]:
## Python basics for novice data scientists, supported by Wagatsuma Lab@Kyutech 
#
# The MIT License (MIT): Copyright (c) 2020 Hiroaki Wagatsuma and Wagatsuma Lab@Kyutech
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */
#
# # @Time    : 2020-4-20 
# # @Author  : Hiroaki Wagatsuma
# # @Site    : https://github.com/hirowgit/2A_python_basic_course
# # @IDE     : Python 3.7.7 (default, Mar 10 2020, 15:43:27) [Clang 10.0.0 (clang-1000.11.45.5)] on darwin
# # @File    : lec1_step4.py 

In [1]:
# module test: if you have an error when you run this code, 
# you need to check the installation status of those modules

import math 
import sys 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tkinter as tk

In [2]:
# Different types of loading methods 
import math 

pi=math.pi
x1=math.sin(pi/2)
x2=math.cos(0)
x3=math.tan(pi/4)

print(pi)
print(x1)
print(x2)
print(x3)

3.141592653589793
1.0
1.0
0.9999999999999999


In [3]:
# Different types of loading methods 
from math import pi 
from math import sin 
from math import cos
from math import tan

#pi=math.pi
x1=sin(pi/2)
x2=cos(0)
x3=tan(pi/4)

print(pi)
print(x1)
print(x2)
print(x3)

3.141592653589793
1.0
1.0
0.9999999999999999


In [15]:
# Different types of loading methods 
from math import *

#pi=math.pi
x1=sin(pi/2)
x2=cos(0)
x3=tan(pi/4)

print(pi)
print(x1)
print(x2)
print(x3)

3.141592653589793
1.0
1.0
0.9999999999999999


In [5]:
import math
import numpy as np

pi=math.pi
x1=math.sin(pi/4)
x2=np.sin(pi/4)
x3=np.sin([0,pi/4,pi/2,3*pi/4])

print(x1)
print(x2)
print(x3)

0.7071067811865475
0.7071067811865475
[0.         0.70710678 1.         0.70710678]


In [6]:
x1=math.sin([0,math.pi/4,math.pi/2,3*math.pi/4])

TypeError: must be real number, not list

In [7]:
x1=np.sin([0,np.pi/4,np.pi/2,3*np.pi/4])
print(x1)

[0.         0.70710678 1.         0.70710678]


In [8]:
s = pd.Series([2, 4, 6, np.nan, 7, 9])
print(s)

0    2.0
1    4.0
2    6.0
3    NaN
4    7.0
5    9.0
dtype: float64


In [9]:
np.array([2, 4, 6, np.nan, 7, 9])

array([ 2.,  4.,  6., nan,  7.,  9.])

In [10]:
inData=np.array([1, 2, 3])
NofD=len(inData)
flagD=np.full(NofD,True)
print(flagD)

[ True  True  True]


In [12]:
inData=np.array([1, 2, 3])
flagD=np.full(len(inData),True)
print(flagD)

[ True  True  True]


In [43]:
inData=np.array([1, 2, 3])
flagD=np.empty(len(inData),dtype=bool)
flagD[:]=True
print(flagD)

[ True  True  True]


In [16]:
inData=np.array([1, 2, 3])
print(len(inData))

3


In [45]:
inData=np.array([[1, 2, 3],[4, 5, 6]])
print(len(inData))
print(np.shape(inData))
print(len(inData[0]))
print(np.shape(inData[0]))

2
(2, 3)
3
(3,)


In [22]:
print(np.shape(inData[0])[0])

3


In [47]:
import sympy as sym

In [48]:
A =sym.MatrixSymbol('a',2,2)
b =sym.MatrixSymbol('b',2,1)

display(A.as_explicit())
display(b.as_explicit())


Matrix([
[a[0, 0], a[0, 1]],
[a[1, 0], a[1, 1]]])

Matrix([
[b[0, 0]],
[b[1, 0]]])

In [49]:
y=A*b
display(A.as_explicit())
display(b.as_explicit())
display(y.as_explicit())

Matrix([
[a[0, 0], a[0, 1]],
[a[1, 0], a[1, 1]]])

Matrix([
[b[0, 0]],
[b[1, 0]]])

Matrix([
[a[0, 0]*b[0, 0] + a[0, 1]*b[1, 0]],
[a[1, 0]*b[0, 0] + a[1, 1]*b[1, 0]]])

In [18]:
A=sym.Matrix([[1, 2], [3, 4]])
b=sym.Matrix([[5], [6]])
display(A)
display(b)
display(A*b)

Matrix([
[1, 2],
[3, 4]])

Matrix([
[5],
[6]])

Matrix([
[17],
[39]])

In [34]:
A_np=np.array([[1, 2], [3, 4]])
B_np=np.array([[5, 6], [7, 8]])
b_np=np.array([[5], [6]])
y_np=np.dot(A_np,b_np)
c=10

print(A_np)
print(b_np)
print(y_np)
print('-')
print(A_np)
print(B_np)
print(A_np+B_np)
print('-')
print(A_np)
print(B_np)
print(A_np-B_np)
print('-')
print(A_np)
print(c)
print(c*A_np)

[[1 2]
 [3 4]]
[[5]
 [6]]
[[17]
 [39]]
-
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
-
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[-4 -4]
 [-4 -4]]
-
[[1 2]
 [3 4]]
10
[[10 20]
 [30 40]]
