In [1]:
# Practice 3-3 (page 24/29)
# https://www.slideshare.net/tadahirotaniguchi0624/3-46861684

In [9]:
import numpy as np

list_0 = [
        [9, 8, 5],
        [0, 8, 3],
        [1, 6, 5],
        [9, 0, 0],
        [4, 9, 3],
        [1, 4, 8],
        [4, 0, 6],
        [0, 3, 5],
        [1, 3, 1],
        [5, 2, 7],
    ]
list_np=np.array(list_0)
print(list_np)


[[9 8 5]
 [0 8 3]
 [1 6 5]
 [9 0 0]
 [4 9 3]
 [1 4 8]
 [4 0 6]
 [0 3 5]
 [1 3 1]
 [5 2 7]]


In [6]:
print(list_np[:,0])

[9 0 1 9 4 1 4 0 1 5]


In [7]:
print(list_np[0,:])

[9 8 5]


In [1]:
a=[1,2,3,4,5,6,7,8,9,10]

In [2]:
a[0]

1

In [3]:
sum(a)

55

In [4]:
A=[[1,2,3],[4,5,6],[7,8,9]]

In [5]:
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
sum(A[0])

6

In [7]:
A=[[1,4,7],[2,5,8],[3,6,9]]

In [8]:
sum(A[0])

12

In [9]:
import numpy as np
A=np.array([[1,4,7],[2,5,8],[3,6,9]])

In [12]:
np.sum(A[0,:])

12

In [13]:
np.sum(A[:,0])

6

In [14]:
np.sum(A)

45

In [18]:
np.size(A,0)

3

In [17]:
np.size(A,1)

3

In [21]:
a=np.array([[1,4,7],[2,5,8],[3,6,9]])
s=0
for i in range(np.size(A,0)):
    for j in range(np.size(A,1)):
        s=s+a[i,j]
s

45